### ISSUE TITLE
Opening New Tab - Font Delay

### ISSUE THREAD

**Issue by Jiriteach** [bluecaret/carettab#102]
Hi - Loving Caret Tab and well done on the work so far. 

I have noticed an issue when opening new tabs, I have a couple of links set and on load of the new tab, the font seems to have a delay before its applied which catches the eye and doesn't look very nice.

I've turned off animations and this has helped but its still there and noticeable where there is a short delay before the font is applied.

Thanks

**Comment by Jiriteach** [comment]
Awesome - Thanks! Any rough estimate on when the next update could possibly be? Thanks

**Comment by bluecaret** [comment]
No guarantees, but I'm hoping another month. I'm on the tail end of recreating it from scratch, just have a few things left to finish.

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
