### ISSUE TITLE
Language setting not honored

### ISSUE THREAD

**Issue by hiergiltdiestfu** [bluecaret/carettab#107]
In the v3 Beta, setting the language to something else than English has no effect on the text contents like the month names or week day names.

![image](https://user-images.githubusercontent.com/10924590/50868743-36245280-13b1-11e9-8168-cd4b20f4443b.png)

**Comment by bluecaret** [comment]
Thank you! The languages/translations have not been implemented in the beta yet, it's one of the last things I still need to do. I'll close this as it isn't so much a bug but just not done yet :)
