### ISSUE TITLE
Part of page is not visible under settings popup

### ISSUE THREAD

**Issue by da411d** [bluecaret/carettab#112]
Part of page is not visible under settings popup. 
![screenshot_5](https://user-images.githubusercontent.com/12462454/51030760-0b99eb80-15a3-11e9-820c-11c78dd64c9f.png)

My idea is to resize the page🤔
![image](https://user-images.githubusercontent.com/12462454/51030900-7ea36200-15a3-11e9-996b-89453d5f27b0.png)

**Comment by da411d** [comment]
Also i think this new design is pretty good, but the old one was more practical

**Comment by da411d** [comment]
1. Mono-column layout
2. Description and example for each item
3. The old design was more neat and simple

![screenshot_4](https://user-images.githubusercontent.com/12462454/51475547-5548ba00-1d8b-11e9-8c31-fbfbe9d844f3.png)
![screenshot_5](https://user-images.githubusercontent.com/12462454/51475548-5548ba00-1d8b-11e9-94d2-42c6d592dcc6.png)

**Comment by bluecaret** [comment]
Thank you for the explanation. So the main reason I did that was for space. There are a lot more settings now than ever especially for clocks. If I did go back to the old display, this would cause a lot of scrolling. Would you still prefer that look knowing that?

Thank you, your opinion is highly appreciated! I wasn't entirely sure about how I was presenting the options now :)

**Comment by da411d** [comment]
By the way, in old version page was resizing on settings open. 
Look: https://drop.me/M03Pel

**Comment by bluecaret** [comment]
Hi, I have changed the way the options panel works, and now the tab content moves over to make room for the options like it previously did. Thank you for the feedback, let me know what you think once you get updated to Beta 3 which was just released today
