### ISSUE TITLE
Layout bug - Settings panel moves off screen

### ISSUE THREAD

**Issue by da411d** [bluecaret/carettab#113]
See details on video: 
https://drop.me/M03AV3 (31.43 Mb)

**Comment by da411d** [comment]
https://dl.daki.me/YHYZIREK

**Comment by bluecaret** [comment]
Hi, I've just updated the beta to Beta 3. In this update I changed the options panel to be back closer to the look of the original version. I think this should hopefully solve this issue. Please let me know if you still see this after being updated to Beta 3.
