### ISSUE TITLE
Week number bug

### ISSUE THREAD

**Issue by da411d** [bluecaret/carettab#114]
![image](https://user-images.githubusercontent.com/12462454/51039879-e74c0800-15be-11e9-9ed3-6c878c74eaf4.png)
![image](https://user-images.githubusercontent.com/12462454/51039881-e7e49e80-15be-11e9-9ff6-eac4ea52d2bb.png)

**Comment by bluecaret** [comment]
Thank you for the report! Yes, it does seem to be the same issue as #105 so I'll close this one and track it there.
