### ISSUE TITLE
V3 Beta: 24-h toggle works partially

### ISSUE THREAD

**Issue by drozel** [bluecaret/carettab#118]
Switching between 12-24 hour modes for clocks changes the clock, but doesn't remove "am/pm" mark (nod needed in the 24-h mode).
![image](https://user-images.githubusercontent.com/6229397/54135093-763b9c00-4419-11e9-9add-74662d564c80.png)

Shall i add "V3 beta" into the titles?

**Comment by bluecaret** [comment]
Thank you, and yes please add that to the title so I know what version it is for. Thanks!

**Comment by bluecaret** [comment]
I'm going to leave this in place in the spirit of full customization, I know it is weird, but who knows, maybe someone will want the am/pm along with 24 hour time. Thank you!
