### ISSUE TITLE
something about customization

### ISSUE THREAD

**Issue by Alice-and-Bob** [bluecaret/carettab#121]
Hey, I want to know if you will allow me to custom my own vision which only for myself to use. Standard code doesn't have the search engine that I want to use, so I want to modification your code to make it suitable for me. And if you don't mind, how can i realize my thinking? THX

**Comment by bluecaret** [comment]
Thanks for asking! It is open source, feel free to fork it and make your customizations. Just be aware that the current code is  a beta for the next update.

Also, what search engine are you wanting? Maybe I could add it as an option.
