### ISSUE TITLE
Date Enhancement

### ISSUE THREAD

**Issue by europ** [bluecaret/carettab#125]
Please, can you change the date form customization from three available options to custom format, which can be defined by using same format attributes as it is implemented in the [linux date command](https://linux.die.net/man/1/date) - format secion?

Example (currently not possible to set):
Date format: `%d.%m.%Y`
Result:`14.10.2019`

BTW thank you for such a good addon!

**Comment by europ** [comment]
Thank you for your replay, I am glad to hear that this will be someday implemented.

Your suggestion is not my case, I want the full year `2019` not its shortened form `19` what is currently not possible.

![Screenshot from 2019-10-29 21-11-12](https://user-images.githubusercontent.com/22373707/67805365-30f3d980-fa91-11e9-87ac-d59a1fb4d826.png)

**Comment by bluecaret** [comment]
@europ thanks for the clarification. That will also be an option in the new version, you will be able to say if you want the 4 or 2 digit year in addition to all the other options. If you'd like to give it a test drive, check out #104 for details on the beta.
