### ISSUE TITLE
Everything Ok? Looks like the last update was back in October 2019

### ISSUE THREAD

**Issue by StewAlexanderACC** [bluecaret/carettab#137]
@bluecaret 

Hoping all is well, looks like the latest update to your **awesome** extension was back in October, 2019.

If you need any help, please let me and or the community know,

Just making sure all is well, love the product btw.

**Comment by bluecaret** [comment]
Hello, thank you for your concern. Everything is fine over here, just life has gotten in the way the last couple years. I am still determined to get this update done and shipped, but it still might be a little while. Most of the update is done, just need to do some bug hunts and set up a first-time-user screen that goes over some basic settings.

**Comment by StewAlexanderACC** [comment]
Appreciate the feedback,,,,
