### ISSUE TITLE
Feature Request (Carettab beta): Image darkening

### ISSUE THREAD

**Issue by StewAlexanderACC** [bluecaret/carettab#138]
hi @bluecaret -

Not sure if the rest of the community would enjoy this or not, but when using the latest beta build of Carettab I noticed you could choose  a picture for the background, however there seemed to be no way to darken it via the extension.

1. How hard is this to do? If it's nearly impossible, never mind
2. If it is somewhat easy to add, it would be a nice feature as it would allow the textual time and date to stand out more from the background

**Comment by bluecaret** [comment]
This should be something I can do. Thanks!

**Comment by StewAlexanderACC** [comment]
Here's what I have setup, just a great tool, thanks for your hard work on it.

![image](https://user-images.githubusercontent.com/48565067/75800455-97427e80-5d47-11ea-8477-eecc0abe604e.png)

**Comment by bluecaret** [comment]
This will be available in the next release, thanks!
