### ISSUE TITLE
[v3 beta] [Suggestion] tick box to (de)activate AM/PM display

### ISSUE THREAD

**Issue by skaldk** [bluecaret/carettab#141]
Issue being : the AM/PM appears even in 24h format
For now you can just left the "am/pm name" blank... or filled with anything, then it works in the end, but the tick box would make it less DIY :)

![image](https://user-images.githubusercontent.com/5103378/79763317-35a09880-8324-11ea-9f2b-a6474766260b.png)

**Comment by bluecaret** [comment]
This is on purpose, as someone (who knows!) might want both options. If you don't want am/pm you can click the enable checkbox at the start of the "Meridiem" section to turn it off. But ya to add flexibility, I don't want to force it off just cause you have 24 hours on. Thanks!

**Comment by skaldk** [comment]
Ow dude, yesss you're right !
What I'm suggesting already exists : switch the "meridiem" on/off

Sorry I ain't see it sooner !
