### ISSUE TITLE
[v3 beta] [issue] two digit for months

### ISSUE THREAD

**Issue by skaldk** [bluecaret/carettab#142]
Doesn't work at all on my side.
If I can help by giving more data let me know 

![image](https://user-images.githubusercontent.com/5103378/79764314-7d73ef80-8325-11ea-88f6-73e223039651.png)

**Comment by bluecaret** [comment]
Bug has been fixed and will be in the next release.

**Comment by skaldk** [comment]
Works like a charm!

Thx 🙂
