### ISSUE TITLE
Add QWANT to search engines

### ISSUE THREAD

**Issue by PascalDk** [bluecaret/carettab#143]
Please add https://www.qwant.com/ to the list of search engines.
It's a privacy concerned search engine made in France

Probably more interesting for french-speaking/reading users, but definitely worth his place on the search engine list imho.

![image](https://user-images.githubusercontent.com/5103378/79765765-54545e80-8327-11ea-9a55-53e1aa526fd2.png)

**Comment by bluecaret** [comment]
On the next update there will be a Premium Access feature for enabling a custom search engine. This should resolve this request.
