### ISSUE TITLE
Absent In Incognito Mode

### ISSUE THREAD

**Issue by ldn15a** [bluecaret/carettab#146]
Carettab works great in "normal" windows, but in incognito windows the default gray "You've gone incognito" is presented. Access and permission to run in incognito windows is granted, and there are no errors, so I'm assuming that this is by design. Please add the option to allow the extension to run in incognito windows.
![Screenshot](https://user-images.githubusercontent.com/43220419/85913599-d798a180-b7fb-11ea-9e52-24ea4cff7450.png)

**Comment by bluecaret** [comment]
Hello, thank you for your bug report. Unfortunately as far as I'm aware there is nothing I can do to override the new tab page in Incognito mode. If you know of a way I'd love to hear it though :)
