### ISSUE TITLE
Feature Request: Show Bookmarks bar

### ISSUE THREAD

**Issue by hpaantee** [bluecaret/carettab#15]
In Chrome exists the setting of not showing the bookmarks bar always. In this case it's only shown at the "new tab" page. Using this extension breaks this functionality. To see the bookmarks bar at all, I have to activate the setting "show bookmarks bar always". It would be nice if the bookmarks bar would behave as for the regular "new tab" page.

**Comment by bluecaret** [comment]
Thank you for the suggestion. Unfortunately this is a limitation of Chrome itself and I don't have any control over it as far as I'm aware (I did just research it a bit to double check). I'll keep this issue open for now though with the hope Chrome will eventually allow this through an API.

Thanks!

**Comment by uroybd** [comment]
At least provide a button to go to apps in the new tab. I've to type chrome://apps every time I need. I tried adding apps as a link but it is not working.

**Comment by bluecaret** [comment]
Thank you @uroybd I'll look into this some more.

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
