### ISSUE TITLE
Feature Request:  Constrain secondary clock bar width

### ISSUE THREAD

**Issue by sxdjt** [bluecaret/carettab#151]
First, the v3 update is _awesome_!  Thank you!

The ability to have multiple clocks is a key feature, and a killer add-on from Carettab.  I have four sub-clocks set up, but it would be nice if the width of the secondary clock area could be constrained so that it doesn't span the entire screen.

Is there was way to set the clock bar's global span, and then the individual clock's span in that element?  In the attached "Wish List.png", that is the way I would like it to look, even when Firefox is set to full screen.  The "Actual.png" is what it looks like when maximised.  Example:  the secondary clock bar is limited to 50% screen width, and then each clock is 25% of the constrained width.

Thank you again for the great product.  Heading over to the Donate link now :) 

**Wish List**
![Wish List](https://user-images.githubusercontent.com/53812540/90981100-1d9d8780-e557-11ea-9c82-76bfaf279d2f.png)

**Actual**
![Actual](https://user-images.githubusercontent.com/53812540/90981108-2726ef80-e557-11ea-8bca-2f512a221acb.png)

**Comment by bluecaret** [comment]
You should have a lot more flexibility with this with the new update, v3.5.0. This just got pushed and should be live in a few days.

**Comment by sxdjt** [comment]
@bluecaret SWEEEEET update!  Thank you so much.  I can't think of anything else that I would change in Carettab.
