### ISSUE TITLE
Feature Request:  Copy/paste clock settings or have a default setup

### ISSUE THREAD

**Issue by sxdjt** [bluecaret/carettab#152]
It would be great if we were able to either copy/paste a secondary clock's setting, or set up a default secondary clock and have the settings apply to the various secondary clocks.

Use case:  I have multiple secondary clocks set up, and add/remove them as my team shifts around the world.  It is time consuming to manually set the size, offset and other customisations each time I add a new clock.

**Comment by sxdjt** [comment]
Yes, a "duplicate clock" feature would be perfect.  Changing the TZ setting on the new clock is easy enough.

Thanks!

**Comment by bluecaret** [comment]
Just finished the work for this feature, you can expect a copy option in the next update!
