### ISSUE TITLE
Cannot change calendar brackets

### ISSUE THREAD

**Issue by sxdjt** [bluecaret/carettab#157]
The option to change the style, colour or visibility of the calendar brackets has gone away (or I can't find it).

**Comment by bluecaret** [comment]
Hi, do you mean the brackets around the clock? There are bracket options for each clock you add. Previously it was only a single set of brackets that was made large enough to wrap around both the clock and the date. You should still be able to replicate this look by adjusting the bracket options on your main clock

![Brackets](https://user-images.githubusercontent.com/9217636/90992353-fe592700-e563-11ea-80fd-2389f22fa93d.png)

**Comment by sxdjt** [comment]
Well that is why I couldn't find them - they are too clearly labelled.  :) 

Issue 157 closable with status "user is derp".
