### ISSUE TITLE
Remove Browsing History Permission

### ISSUE THREAD

**Issue by PieFaceThrowsPie** [bluecaret/carettab#158]
I love this add-on and have it installed on Firefox on several machines.

While updating, the new version is asking permission to access my browsing history. I don't suspect any foul-play, but on principle, I don't want to give permissions when I don't have to.

Please make it possible to install this version without enabling this permission. If it's needed to support a new feature, only ask for the permission when enabling that feature.

I use this add-on just for the background and clock, but I understand other users might want the additional features.

**Comment by 33b5e5** [comment]
The new permissions are terrifying, and I can't find an explanation for them anywhere, so I'll be removing this extension for now. The only thing I really use CaretTab for is replacing the noisy default page in Edge, and showing the date (and nothing else). There is no functionality in my use case that should require the new permissions.

**Comment by bluecaret** [comment]
Thank you all for your feedback, I understand your hesitation. The new permissions are all related to replicating the bookmarks bar. This includes the option of displaying menus for Top Sites, History, Bookmark Manager. The bookmarks bar is the only place those permissions are needed. 

I plan on changing it around to only ask for permissions if you enable the bookmarks bar. It is something I haven't done before and didn't want learning that to hold up this update any longer that I have already procrastinated on for too long. But this is something I want to fix as I do understand the want for minimal permissions. I hope you keep a watch on here for further updates so you can return when it is changed. In fact I think I might make this the very next thing I work on.

**Comment by bluecaret** [comment]
Extra permissions have now been removed and are only requested if you try to use the feature that requires it. You will find this in version 3.1.0. Thanks!

**Comment by phit** [comment]
much appreciated, had been waiting for this to update from pre 3.0
new release looking great!
