### ISSUE TITLE
Quick Link favicons not appearing in Firefox

### ISSUE THREAD

**Issue by Foxfan100** [bluecaret/carettab#162]
FF 79 64 bit on Win10 Pro 1909

Although they appear perfectly in Chrome and Vivaldi, I cannot get the Quick Links favicons to appear on Firefox; although Bookmarks Manager, Apps and Most Visited will do so. See screenshot.

Although Caret Tab works fine without the favicons on Firefox, it would be good to have them. I cannot see that this problem can be caused by an Add-on conflict, but I suppose it's possible. 

I have tried renaming the favicons.sqlite file in the Profile and other things, to no effect.  The QLs were imported when I installed the update, but I have also tried adding some new QLs to the screen "from scratch". These also fail to show the favicons. I used the import method on the Chrome browsers, where the favicons do show correctly.

Edit
I have disabled all Add-ons except for Caret Tab and restarted, but this makes no difference. I think therefore that an Add-on conflict can be ruled out as a cause for non-appearance of favicons.

![caret tab](https://user-images.githubusercontent.com/22635836/91019677-4ec69800-e5e9-11ea-9a5c-144388062cc3.jpg)

**Comment by bluecaret** [comment]
Hi, I can look at this soon, but I know with the favicons they can have problems displaying if you haven't visited the site yet. Please try visiting each site a couple times and then maybe restart the browser and try it again. Hopefully that helps, if not I will look into this soon. Thanks!

**Comment by Foxfan100** [comment]
I've tried various possible methods to obtain the favicons in Firefox, but none make any difference. Possibly not relevant, but I'm using FF 80.0.1. When I call up websites which I have used very frequently, and which should have favicons stored on my machine for instant retrieval, I do get the "hourglass" delay showing on my tabs, albeit briefly, before the site icon replaces it.

**Comment by bluecaret** [comment]
Thank you. This is still an issue that I am trying to figure out. I think it may be related to a Firefox update.

**Comment by mbalc** [comment]
I just updated the extension and I am also having this issue - I'll gladly help with any testing there

**Comment by b2ag** [comment]
Same for me. CaretTab seems to use `chrome://favicon/size/16@2x/https://www.example.org` in img src attribute. Firefox already seem to struggle with the `chrome://` prefix. Maybe because it's Firefox and not Chrome?

**Comment by bluecaret** [comment]
As far as I'm aware its the only way to get favicons "reliably". Unfortunately it seems that Firefox still doesn't like it. Glad to accept any help on this!

**Comment by b2ag** [comment]
thanks for fixing this ❤️
