### ISSUE TITLE
update to v3.0, previous labels were lost， how to recover？

### ISSUE THREAD

**Issue by kaydxh** [bluecaret/carettab#163]
![image](https://user-images.githubusercontent.com/16474709/91066144-ed8fda80-e663-11ea-95c1-be33b1a4bcf8.png)
there were previous lables in UI, but now there is nothing  when update to v3.0, how  to recover them?

**Comment by bluecaret** [comment]
Do you mean the quick links? If so there was an option to recover those  right after the update.

Or do you mean labels for clocks? That option is still available as an option for each clock under the individual clock options.

**Comment by kaydxh** [comment]
Yea, I mean the quick links.  where is the option to recover my quick links? Now only these quick links, but I have more quick links before  update to version v3.0
![image](https://user-images.githubusercontent.com/16474709/91124754-8b21f300-e6d2-11ea-9e40-0ab2475b4eb9.png)

**Comment by bluecaret** [comment]
Thank you. Unfortunately the update changed a lot including the structure of the data which made it too complex to copy existing settings over. However, during the update you should have been presented an option to import your old links but it would have only been on that first page.

If you are comfortable with browser's console you could run the following code in the console for the new tab page and still retrieve a list of your old links which you can then manually re-add:

```
chrome.storage.sync.get((a) => {
  let printRecoveredQuickLinks = '';
  if (a.links && a.links.length > 0) {
    for (let i = 0; i < a.links.length; i++) {
      printRecoveredQuickLinks += a.links[i].label + ' <' + a.links[i].url + '>\n'  ;
    }
    console.log(printRecoveredQuickLinks);
  } else {
    console.log('No Quick Links found');
  }
});
```

**Comment by kaydxh** [comment]
Thanks. I have gotten my old links by this way.
