### ISSUE TITLE
3.0.0 upgrade lost tab-title-as-date setting

### ISSUE THREAD

**Issue by markhu** [bluecaret/carettab#164]
After the 3.0.0 update, I panicked because the date-in-tab was literally the biggest/only reason I use CaretTab.
I rely on that feature as the coolest way to automatically date-stamp my screenshots of a browser page. Just seeing the plain old "New Tab" put me into a sweat.
To find the setting, I went to another computer that hadn't had the update yet, and poked around in its settings. Thankfully that clued me into where to find the setting in the new icon-heavy UI.

**Comment by bluecaret** [comment]
Hi, this should still be an option under the extras settings page. 

Or do you mean that even after setting it to date that it still does not show the date? 

The update had some complexities in it that required me to have to reset options so you may just need to set that option back on. Thanks!

**Comment by markhu** [comment]
The setting works fine when manually set, but was not migrated during update from older version.

**Comment by bluecaret** [comment]
So it sounds to me like this is working, its just that it didn't carry over on the update? I will go ahead and close this then. Let me know if you are still having issues and I'll reopen. Thank you.
