### ISSUE TITLE
Unchecked runtime.lastError: QUOTA_BYTES_PER_ITEM quota exceeded

### ISSUE THREAD

**Issue by searKing** [bluecaret/carettab#166]
MacBook Pro (16-inch, 2019)
macOS Catalina 10.15.6 (19G73)
Google Chrome 84.0.4147.135
CaretTab v3.0

If Quick Link List contains too many links, (64 links for example),  when "Save and close setting" button is clicked, chrome will throw an error like "Unchecked runtime.lastError: QUOTA_BYTES_PER_ITEM quota exceeded", save action takes no effect.

![image](https://user-images.githubusercontent.com/4208726/91155130-fda3ca80-e6f4-11ea-8126-25134846a336.png)

**Comment by bluecaret** [comment]
Thank you for the feedback. Unfortunately this is a limitation in the amount of data Chrome lets me save to the browser. It is not a hard limit though, it depends on what other settings you have as well. 

There is not much I can do other than suggest using less quick links. I could also suggest using the bookmarks bar instead as that is also an option now, and that just pulls from your browser's bookmarks so there is no limit as far as the extension is concerned.

**Comment by searKing** [comment]
Older CaretTab can support more quick links.

**Comment by bluecaret** [comment]
I can see that, there are a lot more options I am saving in this new version which would decrease the amount of space available. I'm sorry but right now I do not plan to change this. If you would like to submit a pull request with changes that could resolve this I'd be more than happy to accept the help.
