### ISSUE TITLE
How can I downgrade?

### ISSUE THREAD

**Issue by yesmiley** [bluecaret/carettab#168]
Sorry to say that I don't like the new version.
How can I downgrade to v2?

**Comment by bluecaret** [comment]
Sorry for the delay. I believe Firefox will let you install older versions but I don't think it is possible with Chrome. I hope you closing this means you have changed your mind. If there is anything in particular you would like to comment on I can see what I can do about it.

**Comment by yesmiley** [comment]
Thanks for your reply.
I just found an old verison and did some tricks to prevent it upgrade automatically, therefore I colsed this issue :)
