### ISSUE TITLE
Caret Tab stopped working - white screen on new tab

### ISSUE THREAD

**Issue by sxdjt** [bluecaret/carettab#173]
Hi - as of this morning, Caret Tab is no longer working for me.  Not sure what changed, but all I get is a blank white browser window instead of my nice Caret Tab.

I have uninstalled/reinstalled and no change in behaviour.  I've included what I can find that may be useful for diagnostics?

Caret Tab: 3.0.1
Browser:  Firefox 80.0.1
OS:  Catalina 10.15.6

[console-export-2020-9-10_7-49-0.txt](https://github.com/bluecaret/carettab/files/5199713/console-export-2020-9-10_7-49-0.txt)

**Error message seen in "Debug Addons":**

`Reading manifest: Warning processing permissions: Error processing permissions.2: Value "chrome://favicon/" must either: must either [must either [must either [must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["clipboardRead", "clipboardWrite", "geolocation", "notifications"], be one of ["bookmarks"], be one of ["browsingData"], be one of ["devtools"], be one of ["find"], be one of ["history"], be one of ["pkcs11"], be one of ["sessions"], be one of ["tabs", "tabHide"], be one of ["topSites"], be one of ["browserSettings"], be one of ["downloads", "downloads.open"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], or be one of ["webNavigation"]], be one of ["alarms", "mozillaAddons", "storage", "unlimitedStorage"], be one of ["captivePortal"], be one of ["identity"], be one of ["menus", "contextMenus"], be one of ["normandyAddonStudy"], be one of ["geckoProfiler"], be one of ["urlbar"], be one of ["contextualIdentities"], be one of ["dns"], be one of ["activityLog"], be one of ["networkStatus"], be one of ["telemetry"], or be one of ["theme"]], must either [must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["clipboardRead", "clipboardWrite", "geolocation", "notifications"], be one of ["bookmarks"], be one of ["browsingData"], be one of ["devtools"], be one of ["find"], be one of ["history"], be one of ["pkcs11"], be one of ["sessions"], be one of ["tabs", "tabHide"], be one of ["topSites"], be one of ["browserSettings"], be one of ["downloads", "downloads.open"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], or be one of ["webNavigation"]], be one of ["nativeMessaging"], or match the pattern /^experiments(\.\w+)+$/], or must either [be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/]`

**Source from moz-extension://c0f98901-08b5-3f45-85df-34f7f9b2b97d/manifest.json:**

```
{
  "manifest_version": 2,

  "name": "__MSG_appName__",
  "short_name": "CaretTab",
  "description": "__MSG_appDesc__",
  "version": "3.0.1",
  "default_locale": "en",

  "icons": { "16": "assets/img/icon16.png",
             "48": "assets/img/icon48.png",
            "128": "assets/img/icon128.png" },

  "chrome_url_overrides" : {
    "newtab": "index.html"
  },

  "background": {
    "scripts": ["js/update.js"]
  },

  "permissions": [
    "storage",
    "bookmarks",
    "chrome://favicon/",
    "topSites"
  ],

  "content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'",

  "applications": {
    "gecko": {
      "id": "{1ab49626-2e16-405b-ad65-dcaab8decd7b}",
      "strict_min_version": "57.0"
    }
  }

}
```

**Comment by Thomas-O** [comment]
I have Carettab on two PCs. Both running Firefox 80.0.1 + Elementary OS.
One is fine but the other is now a blank white screen.
The only difference between the two is a custom wallpaper image with the now blank screen.

**Comment by sxdjt** [comment]
I had a custom wallpaper as well.  Three similar systems with FF sync enabled and now all three are whitescreen.

Is there a way to manually reset Caret Tab to default/OOTB to remove the custom wallpaper?  Un/reinstalling it didn't clean up whatever the setting is.

**Comment by Thomas-O** [comment]
I downgraded the add-on to the previous version. Remove Carettab and install the old (2.3.1) version at this [link](https://addons.mozilla.org/en-US/firefox/addon/carettab/versions/?src=search).

**Comment by sxdjt** [comment]
I uninstalled 3.0.1 and installed 2.3.1 per suggestion.  Caret Tab 2.3.1 works fine, and seems to have found its original configuration.  

Updating through the FF add-on manager to 3.0.1 gives a white screen again.

**Comment by bluecaret** [comment]
Thank you for reporting! I am looking into it now. Though right now I do see it working on my machine. It's strange as the error seems to be related to getting favicons for links but that shouldn't be any issue.

**Comment by sxdjt** [comment]
On my work laptop, Caret Tab 3.0.1 is working just fine, but on my three other systems it isn't working. The work laptop is not set up to use FF Sync, but the other three are syncing together.  I am guessing that one of the machine configs got corrupted and it propagated itself along.

Not sure how to find/delete the Caret Tab extension configs?  If I can find them I can send them along for diags if helpful.

**Comment by bluecaret** [comment]
If you know how to use the console, open that up on the tab and run the following command:

```
chrome.storage.sync.get((data) => {console.log(data)})
```

That should get you a listing of all the configurations in an object for CaretTab on your machine. Expand the object and all the children inside it, copy paste those here or send me a direct message with it.

Thank you!

**Comment by sxdjt** [comment]
Upgraded from 2.3.1 to 3.0.1, restarted FF and got this from the console.  In 3.0.1, when it was running, I had a different clock config, and this seems to be pulling the old clocks.

[console_debug.txt](https://github.com/bluecaret/carettab/files/5203398/console_debug.txt)

```
Thank you for using CaretTab! main-es2017.js:1:787540
ERROR TypeError: Rb.find(...) is undefined
    Gb moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    Om moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    zm moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    D_ moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    C_ moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    j_ moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    create moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    create moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    bootstrap moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    _moduleDoBootstrap moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    _moduleDoBootstrap moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    bootstrapModuleFactory moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    invoke moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    onInvoke moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    invoke moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    run moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    z moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    invokeTask moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    onInvokeTask moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    invokeTask moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    runTask moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    y moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
main-es2017.js:1:592903
    ai moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    handleError moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    bootstrapModuleFactory moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    invoke moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    run moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    runOutsideAngular moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    bootstrapModuleFactory moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    invoke moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    onInvoke moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    invoke moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    run moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    z moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    invokeTask moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    onInvokeTask moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    invokeTask moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    runTask moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    y moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
TypeError: Rb.find(...) is undefined
    Gb moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    Om moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    zm moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    D_ moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    C_ moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    j_ moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    create moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    create moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    bootstrap moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    _moduleDoBootstrap moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    _moduleDoBootstrap moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    bootstrapModuleFactory moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    invoke moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    onInvoke moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    invoke moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    run moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    z moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    invokeTask moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    onInvokeTask moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/main-es2017.js:1
    invokeTask moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    runTask moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
    y moz-extension://cbd76e30-5fb8-0d49-92a0-2d8f9b8b240c/polyfills-es2017.js:1
main-es2017.js:1:1391178
chrome.storage.sync.get((data) => {console.log(data)})
undefined
Object { caretTabStatus: "updated", carettab: {…}, links: (1) […], s2ndClock: "on", s2ndClockLabel: "PRG", s2ndClockTimezone: "Europe/Paris", s3rdClock: "on", s3rdClockLabel: "BOS", s3rdClockTimezone: "America/New_York", s4thClock: "on", … }
debugger eval code:1:44
```

**Comment by bluecaret** [comment]
This line here: `Object { caretTabStatus: "updated", carettab: {…}, links: (1) […], s2ndClock: "on", s2ndClockLabel: "PRG", s2ndClockTimezone: "Europe/Paris", s3rdClock: "on", s3rdClockLabel: "BOS", s3rdClockTimezone: "America/New_York", s4thClock: "on", … }` should have given you an option to expand the details, can you do that for everything within it? That's the part that has your config in it.

Also to clarify, upgrading from 2.3.1 to 3.0.1 will give you different configs as I had to reconfigure the way things were saved adn with new features and other things I was not able to port the old settings over easily, so 3.0.1 would start out with a white background and simple clock, but it shouldn't be completely white with nothing on the screen.

The above line in your console after running that command should provide the config from both versions of CaretTab assuming the old config hasn't been wiped out yet which doesn't look like it has.

**Comment by bluecaret** [comment]
If you want to go ahead and give it a try as well, we could wipe everything to completely start you over, that might help. Try running this command and then restart Firefox: (**you will need to recreate all your settings again**)

```
chrome.storage.sync.clear(); localStorage.clear();
```

**Comment by sxdjt** [comment]
Ah, didn't see that expander (results below).  I will try clearning local storage and see what that does, and report back.

```
{…}
caretTabStatus: "updated"
​carettab: Object { bookmarks: {…}, date: {…}, lang: "en-US", … }
​links: Array [ {…} ]
​s2ndClock: "on"
​s2ndClockLabel: "PRG"
​s2ndClockTimezone: "Europe/Paris"
​s3rdClock: "on"
​s3rdClockLabel: "BOS"
​s3rdClockTimezone: "America/New_York"
​s4thClock: "on"
​s4thClockLabel: "SFO"
​s4thClockTimezone: "America/Los_Angeles"
​sAnalog: "off"
​sAnimation: "off"
​sBackground: "#222222"
​sBlinking: "off"
​sBracketStyle: "square"
​sBrackets: "on"
​sCustomMessage: "off"
​sCustomMessageText: "Welcome to the World Wide Web!"
​sDate: "on"
​sDateDelimiter: "slash"
​sDateFormat: "middle"
​sDay: "on"
​sDelimiter: "on"
​sDimBrackets: "on"
​sDimDelimiter: "on"
​sDimSeconds: "off"
​sEngine: "google"
​sFont: "exo-2"
​sForeground: "#ffffff"
​sHideSettingsToggle: "off"
​sLoad: "1.2.0"
​sMeridiem: "on"
​sMilitary: "on"
​sPrimaryClock: "on"
​sPrimaryClockTimezone: "Europe/London"
​sScale: "75"
​sSearch: "off"
​sSeconds: "on"
​sShortDate: "off"
​sTabTitle: "new-tab"
​sTabTitleCustomMessage: "Welcome to the World Wide Web!"
​sWeek: "off"
​sWeekLabel: "week"
​sYear: "off"
​<prototype>: Object { … }
debugger eval code:1:44
```

**Comment by bluecaret** [comment]
Sorry one more request, inside that object, there is another one with an expander titled "carettab", 2nd line, and inside that some more, can you expand all of those?

**Comment by sxdjt** [comment]
From a 3.0.1 whitescreen installation

[log1.txt](https://github.com/bluecaret/carettab/files/5203716/log1.txt)

**Comment by sxdjt** [comment]
At this point, it seems like this issue was due to something being corrupted in my local storage, and Firefox Sync propagating it to my linked devices.  This one is closable from my viewpoint.

Thanks for the quick response!
