### ISSUE TITLE
Address bar input entered on a new tab so far gets cleared on CaretTab load

### ISSUE THREAD

**Issue by mbalc** [bluecaret/carettab#174]
Here's a few test cases that I have problems with when using this extension on my production environment:

test1:
- copy some text
- having a few tabs open in Firefox, press Ctrl+T to open new tab, then immediately press Ctrl+V
- in just a moment, CaretTab will load and that will seemingly clear all address bar content
- (variant 1) if you press Enter now however, the browser will behave as if the content pasted weren't cleared just before
- (variant 2) if instead of pressing Enter you try to follow up with putting in additional content and only then press Enter - only the content that you've typed afterwards will get searched by the browser

[here's variant 2 in action - I'm opening a new card and then immediately pasting, then typing the rest of the expression I want to search](https://streamable.com/3hbixc)

test2:
- having a few tabs open in Firefox, press Ctrl+T to open new tab, then immediately start writing some text on the keyboard
- the CaretTab load will interrupt your writing, effectively cutting away an initial part of what you have been writing
- when pressing Enter, only the visible part gets searched, causing a lot of frustration and forcing me to correct the input

[here's test2 in action - after opening I'm trying to quickly type 'qwertyuiop'](https://streamable.com/2xnauk)

Expected behaviour: 
- a successful load of CaretTab in my browser should leave the input entered so far unaffected
- the user doesn't have to remember to wait until the extension fully loads before he can safely start entering stuff into search bar

Notes: 
- Disabling all other extensions I've got enabled but CaretTab significantly decreases the length of the time window for input that is going to be cleared when CaretTab loads (I guess that's because more extensions have to load); however the issue still persists (it's just much harder to replicate - instead of a couple of letters I only get to write just a single one before the problem happens)
- Disabling only CaretTab (all other extensions enabled) effectively eliminates the issue (see [here](https://streamable.com/lbpnhw))

[my Firefox extensions list](https://user-images.githubusercontent.com/11033790/93665960-c073f380-fa7a-11ea-87ec-e00bd77f93bc.png)

**Comment by bluecaret** [comment]
Thank you very much for the detailed report. Unfortunately I'm not sure there is anything else I can do about this. It's partly how long the browser takes to load the extension on each new tab, and as you saw partly based on how many other extensions you have. With the latest update I have tried to increase the performance on load of the extension but performance is not something I'm particularly good at so I'm not sure what else to do here. It truly is just based on how fast CaretTab loads when a new tab is open. And it is a Firefox issue that it doesn't take what was typed before load and keep it after load. Hope that makes sense. If you know of any performance changes I can make in the code I would be happy to accept a pull request. Thank you!
