### ISSUE TITLE
Export and/or sync setup

### ISSUE THREAD

**Issue by PascalDk** [bluecaret/carettab#175]
Would help a lot to be able get an export of our CaretTab setings (I have 6 different) in order to install them easier on different computers (I use 5 different on weekly basis).

Having a _"go to file"_ or _"export settings"_ button in the option panel would already help a lot.

Sync with Google Drive would be even more helpful :)

**Comment by bluecaret** [comment]
Yes this is something I would like to add. Always welcome to a pull request if you want to give it a shot :) Thank you.

**Comment by skaldk** [comment]
I'd love to be able to help on that side but unfortunately I'm not skilled at all for such things 😕

**Comment by PascalDk** [comment]
_...a long time ago in a galaxy far away..._

yep, i'm gonna do that :)

**Comment by bluecaret** [comment]
Finished the code for this today, expect export/import options in the next update. There will be buttons to export which downloads a file, and import which will expect the same file that was exported.
