### ISSUE TITLE
[Bug] Daylight saving time / Summer Time for Brazil

### ISSUE THREAD

**Issue by LeonnardoVerol** [bluecaret/carettab#177]
Since 2019, Brazil does Not have Daylight saving time / Summer Time.

Due to this misconfiguration, is necessary to choose another State/Country to show the right time.

**Comment by bluecaret** [comment]
Hopefully should be fixed in version 3.1.0

**Comment by LeonnardoVerol** [comment]
Not yet fixed. @bluecaret
