### ISSUE TITLE
Timezone GMT -6 Central Time

### ISSUE THREAD

**Issue by dbinary** [bluecaret/carettab#18]
Please add an option to this timezone for ignore Daylight Saving, because it does not apply to Central America.

**Comment by bluecaret** [comment]
Hi, thanks for the feedback. I will definitely look into this!

**Comment by bluecaret** [comment]
This has been fixed and should be released with the next update soon. It will come in the form of a "Central Standard Time" option. Thank you!

**Comment by bluecaret** [comment]
Got this one done quicker than anticipated. The update has just been pushed out. Take a look at the "Central Standard Time" option :)
