### ISSUE TITLE
Feature Request: year/month/day specific delimiters/suffixes

### ISSUE THREAD

**Issue by theaidan9030** [bluecaret/carettab#189]
First off, I'd like to say that I've been using CaretTab for about a year and a half now, and it's better than pretty much any other New Tab extension I've used. (in my opinion)

Anyway, I'm requesting being able to use different delimiters/suffixes for the year, month and day on the date.

That way, I can use the Japanese date notation system. (ex: 2008年12月31日)

Thanks in advance!

**Comment by bluecaret** [comment]
Good idea, thanks for the suggestion!

**Comment by bluecaret** [comment]
This feature has been added and will be available in the next update. Thank you!
