### ISSUE TITLE
CaretTab doesn't work on Firefox

### ISSUE THREAD

**Issue by libralibra** [bluecaret/carettab#193]
Used it for years. It worked fine for v2.
After upgrading to v3, it works in chromium-based MS Edge, but not Firefox anymore. Always give me a blank page without any error message.
tried uninstall - install, and restart browsers for many time. The error is consistent. A blank page all the time.

**Comment by bluecaret** [comment]
Hello, sorry your seeing issues. Can you please check the console in the browser and see if you have any errors showing there?

- Open up a new tab
- Press ctrl+shift+k
- This should open the console, screenshot the console that opens and post in a reply here.

The console window will look like the following:
![image](https://user-images.githubusercontent.com/9217636/113914352-4dba3380-9792-11eb-87b4-e159a47548f4.png)

**Comment by bluecaret** [comment]
An update was just released as v3.4.0, please let me know if you continue to have issues after that update.
