### ISSUE TITLE
Add UTC/GMT options for timezone

### ISSUE THREAD

**Issue by bluecaret** [bluecaret/carettab#197]
As suggested by Erik Yates via email:

Add Universal Time Coordinated (UTC) or Greenwich Mean Time clock. As a pilot, I rely heavily on UTC, and, while the GMT+0:00 for Cote d'Ivorie is a workaround, it would be nice to have a dedicated UTC line in the long list of cities for the time zones.

**Comment by Zaglim** [comment]
It appears this feature was temporarily removed for v3.5.0, and has yet to be reintroduced. Hopefully you or someone works out a solution! It's the only thing missing that I'm missing :)
