### ISSUE TITLE
Feature request: Digital Clock Font and Alarm Function

### ISSUE THREAD

**Issue by duytrung** [bluecaret/carettab#20]
Hi,

I really like the extension. Should it implement the digital clock font and alarm function (specific time, time lapse, countdown timer, and pomodoro timer), show a big digital clock in chrome toolbar?

Kind regards

Will

**Comment by bluecaret** [comment]
Thank you for the suggestions, I will keep them in consideration.

**Comment by bluecaret** [comment]
The digital clock font has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104

**Comment by bluecaret** [comment]
Oh and I also meant to say I won't be adding any alarm clock feature, I consider that out of the scope of this project for now. Maybe another day, though I think a separate extension would be ideal for that.
