### ISSUE TITLE
Auto focus search box when typing

### ISSUE THREAD

**Issue by Stone-Red-Code** [bluecaret/carettab#203]
It would be cool if the search box would automatically focus when you start typing anywhere on the page.
Preferably this should be an option in the search bar settings.

Thanks in advance!

**Comment by bluecaret** [comment]
Thank you for the suggestion! I would love to allow this but right now, as far as I'm aware, the browser's do not allow the new tab page to take focus away from the address bar on load so this is unable to be done. Thanks for your support!
