### ISSUE TITLE
When you open a new tab, the address bar automatically focuses and alt+1 hotkeys do not work

### ISSUE THREAD

**Issue by chervyakovru** [bluecaret/carettab#204]
First, I want to say a big thank you for this app! I love it, I love that UI and UX design. This is the best browser new tab override extension I've ever seen!

I have disabled BOOKMARKS BAR, and SEARCH BOX and MESSAGE. Have only one `Quick links` and `Clock`. And when i open new tab i can't use hotkeys for quick access for Quick links because address bar is focused

Can i change any settings for able use hotkeys with focused address bar?

And will be perfect if hotkeys work global. Like i on some page, press alt+1 and in new tab opens my `Quick link`!

**Comment by bluecaret** [comment]
Thank you for the comments!

Unfortunately the page needs to be in focus for these keyboard shortcuts to work but the address bar has focus on new tabs and the browser does not allow this to be changed. This is something I want to look into more to see if I can do something else to make the shortcuts better.

**Comment by chervyakovru** [comment]
Do you knew that Chrome have API for add global shortcats? Here is the link to doc: https://developer.chrome.com/docs/extensions/reference/commands/ 

Think there is  can help

**Comment by bluecaret** [comment]
I was not aware of that thank you very much, that looks like a much better solution!!

**Comment by bluecaret** [comment]
This has been fixed. I'm now utilizing the browser's API for extension shortcuts. Due to the some limitations with that API, only links 1-4 will automatically have the shortcuts assigned. Links 5-9 can be manually set in the browser settings.

This will be in the next update which I'd expect to be live sometime within the next couple weeks.
