### ISSUE TITLE
Feature request: Cicle trough multiple custom messages

### ISSUE THREAD

**Issue by felipemldias** [bluecaret/carettab#205]
Dear Bluecaret,

 Thank you so much for this extension, it's really awesome!

 If I could suggest a minor improvement, it would be for each new tab to be able to display a random custom message out of a list of custom messages, not always the same one.

 Some other new tab extensions have this and it's pretty cool (not as cool as CaretTab though!). 

Best regards,

Felipe

**Comment by bluecaret** [comment]
Thank you for the suggestion! I can look into this for a future update.

**Comment by Ruandv** [comment]
@felipemldias @bluecaret  If this feature is implemented is there any specific requirements that should be kept in mind? Like the number of characters that will be allowed and should the text auto shrink when it gets too long?

**Comment by bluecaret** [comment]
I don't have a limit on the current message text so it would be fine to go without, and it should act just like it currently does, being a set size based on what the user sets their size too

**Comment by felipemldias** [comment]
You guys are awesome! Will love to see it implemented, many thanks!
