### ISSUE TITLE
Feature request: Custom search engines or from the ones defined in the chrome settings

### ISSUE THREAD

**Issue by Randshot** [bluecaret/carettab#21]
Hi,
I really like your extension, but one thing is nagging me.
I would love to be able to define my own custom search engine/url like I can do in the chrome settings.

Randshot

**Comment by bluecaret** [comment]
Thanks for the suggestion. This can be a little tricky to do because of how different searches work, but I'll look into it as a potential future update.

**Comment by bluecaret** [comment]
A custom search engine option has been added. It will be availlable in the next update via a Premium Access feature.
