### ISSUE TITLE
got blank page (pure white without anything) after installing in Firefox

### ISSUE THREAD

**Issue by libralibra** [bluecaret/carettab#210]
it worked fine in my MS Edge, but not Firefox.

**Comment by bluecaret** [comment]
Sorry for the inconvenience. I'm currently working on what I hope is a fix for this. In the meantime you can try performing the following steps in Firefox:

Press ctrl+shift+K while on the new tab page. This will open the console window. At the bottom of the console window type in and press enter:

```
chrome.storage.sync.clear()
```

This will clear out all settings on the new tab page and hopefully will get you back in working order.

**Comment by bluecaret** [comment]
An update just went out last night for CaretTab, please let me know if you are still experiencing the issue after the update.

**Comment by libralibra** [comment]
thanks. the latest update fixed the problem in Firefox.
