### ISSUE TITLE
The carettab background picture shows blank when a new Edge window created

### ISSUE THREAD

**Issue by Curious-r** [bluecaret/carettab#218]
screenshot:
![image](https://user-images.githubusercontent.com/19733878/121995029-e3002680-cdd8-11eb-987d-8cef39980412.png)

**Comment by Curious-r** [comment]
And the normal state is as follow:
![image](https://user-images.githubusercontent.com/19733878/121995490-949f5780-cdd9-11eb-82dd-8ebfa379ebc5.png)

**Comment by bluecaret** [comment]
I'm sorry for the trouble. Can you open the console and take a screen shot of that once you open a new window? Open the console by right-clicking the screen, select "insect" and then select the "console" tab. Thank you.

**Comment by Curious-r** [comment]
> I'm sorry for the trouble. Can you open the console and take a screen shot of that once you open a new window? Open the console by right-clicking the screen, select "insect" and then select the "console" tab. Thank you.

Hello, console screenshot:
![image](https://user-images.githubusercontent.com/19733878/122318532-c20f1100-cf51-11eb-95f7-034613272f69.png)

**Comment by bluecaret** [comment]
Thank you for the screenshot. I'm actually seeing that issue myself as well now. I'll get a quick patch out for this ASAP. Thank you for submitting this!

**Comment by Curious-r** [comment]
> Thank you for the screenshot. I'm actually seeing that issue myself as well now. I'll get a quick patch out for this ASAP. Thank you for submitting this!

Thank you for developing such a beautiful extension!

**Comment by bluecaret** [comment]
Hmm, went to go debug it and now it is not happening for me, very strange. Unfortunately not much I can do to fix it without actively seeing it. I'm still going to keep an eye on this and I have other changes in the works that may help prevent this too. 

For now for you, can you see about disabling the extension in your browser and then re-enabling it, and then try selecting a different pattern and then change back to your original one, make sure to close the settings panel after, and then see if that works?

Thank you!

**Comment by Curious-r** [comment]
> Hmm, went to go debug it and now it is not happening for me, very strange. Unfortunately not much I can do to fix it without actively seeing it. I'm still going to keep an eye on this and I have other changes in the works that may help prevent this too.
> 
> For now for you, can you see about disabling the extension in your browser and then re-enabling it, and then try selecting a different pattern and then change back to your original one, make sure to close the settings panel after, and then see if that works?
> 
> Thank you!

No, it doesn't work, not even if I've reinstalled the extension. Maybe it's browser version related？
My browser is Microsoft Edge 91.0.864.48.
![image](https://user-images.githubusercontent.com/19733878/122445756-6f2a6d80-cfd4-11eb-82e4-5be37cfec415.png)

**Comment by bluecaret** [comment]
I'm on that same version so that's not it, but I didn't realize you were on Edge so that's good to know. This shouldn't matter but just in case are you using the [Edge](https://microsoftedge.microsoft.com/addons/detail/bfpmncaohmjelebfobabccfjgmeolloe) or [Chrome](https://chrome.google.com/webstore/detail/carettab-new-tab-page/cojpndognjdcakkimaloeealehpkljna?hl=en-US) version of CaretTab? The extension is hosted on both browser's stores and both versions will work in Edge, maybe try the opposite version from what you are using?

Also just to be sure, you are closing the settings panel before closing the tab after changing the pattern right? Settings are not saved until the panel is closed first, closing the tab without closing the panel will revert back to the last save.

**Comment by Curious-r** [comment]
> I'm on that same version so that's not it, but I didn't realize you were on Edge so that's good to know. This shouldn't matter but just in case are you using the [Edge](https://microsoftedge.microsoft.com/addons/detail/bfpmncaohmjelebfobabccfjgmeolloe) or [Chrome](https://chrome.google.com/webstore/detail/carettab-new-tab-page/cojpndognjdcakkimaloeealehpkljna?hl=en-US) version of CaretTab? The extension is hosted on both browser's stores and both versions will work in Edge, maybe try the opposite version from what you are using?
> 
> Also just to be sure, you are closing the settings panel before closing the tab after changing the pattern right? Settings are not saved until the panel is closed first, closing the tab without closing the panel will revert back to the last save.

I'm sure that I have closed the setting panel before closing the tab. And I think this problem is not due to settings saving, because opening a new tab on a already-open browser windows is normal. The comparison is as follows:
![image](https://user-images.githubusercontent.com/19733878/122453673-275c1400-cfdd-11eb-9d98-46ce7999478d.png)
![image](https://user-images.githubusercontent.com/19733878/122453729-2a570480-cfdd-11eb-8e82-4253ac248362.png)


I get the carettab from Microsoft Store:
![image](https://user-images.githubusercontent.com/19733878/122453924-55415880-cfdd-11eb-949d-e5e13d0b0955.png)

**Comment by bluecaret** [comment]
Thank you for the extra information! I'll keep diving into this and see what I can come up with, I hope you'll be patient with me, I'll find you a solution!

**Comment by bluecaret** [comment]
One more debugging request... Within both a tab that shows the pattern, and one that does not show it, do the following: 

In that console window I had you open before, on the bottom is a spot to type in, please paste the following in that spot, hit enter, and then let me know what it says after that:

```chrome.storage.sync.get(d => {console.log(d['ct-design'].patternId, d['ct-design'].imageSize, d['ct-design'].imageBlend, d['ct-design'].background)})```

**Comment by Curious-r** [comment]
> One more debugging request... Within both a tab that shows the pattern, and one that does not show it, do the following:
> 
> In that console window I had you open before, on the bottom is a spot to type in, please paste the following in that spot, hit enter, and then let me know what it says after that:
> 
> `chrome.storage.sync.get(d => {console.log(d['ct-design'].patternId, d['ct-design'].imageSize, d['ct-design'].imageBlend, d['ct-design'].background)})`

Return information: 
![image](https://user-images.githubusercontent.com/19733878/122456857-9b4beb80-cfe0-11eb-8c89-b7eb1e067bca.png)
![image](https://user-images.githubusercontent.com/19733878/122456874-9f780900-cfe0-11eb-902c-5b391b85eb43.png)

I have used carettab for a long time, since version 2.0. In my memory, this problem only appeared recently.

**Comment by bluecaret** [comment]
Thank you, that helps, I think I may have an idea what might be going on now. Thank you for your long time usage of CaretTab!!

**Comment by Curious-r** [comment]
> Thank you, that helps, I think I may have an idea what might be going on now. Thank you for your long time usage of CaretTab!!

I am glad to be able to help, 😉

**Comment by bluecaret** [comment]
Hey there, sorry for the delay. I believe I have found the error, I accidentally caused that bug while trying to fix another bug! I got both fixed now and it will go out in the next update. I'm hoping to get the next update out by the end of this week but please don't hold me to that. :)

**Comment by Curious-r** [comment]
> Hey there, sorry for the delay. I believe I have found the error, I accidentally caused that bug while trying to fix another bug! I got both fixed now and it will go out in the next update. I'm hoping to get the next update out by the end of this week but please don't hold me to that. :)

That's great news, now carettb is perfect again!

**Comment by bluecaret** [comment]
I am very sorry for the delay in this, I said I'd get it out in a week and here it is literally 2 months later! 😨 

However, good news is I finally got the update out! I just pushed v3.5.0 to all stores, each one takes it's own time to publish but give it 2-5 days and you should have the new update in your browser and hopefully this bug will be fixed!

Thanks for using CaretTab!
