### ISSUE TITLE
Smaller scale

### ISSUE THREAD

**Issue by RyanRoberts** [bluecaret/carettab#22]
Can we have an even smaller value on the size scale, please? :)

**Comment by bluecaret** [comment]
Thought it was pretty small already, but ya I can do that on the next update :)

**Comment by RyanRoberts** [comment]
I've just realised you're using % font size, so it's relative to the screen size. This makes sense.

I don't want to make your plugin unnecessarily complex but maybe an alternative option for a fixed size that doesn't scale would work?

**Comment by bluecaret** [comment]
Is there a reason a fixed size would be preferred? I have it relative so that no matter your screen size, everything will still fit. 

Thanks!

**Comment by bluecaret** [comment]
I have just released an update that increases the range for the display scaling. You can now make it smaller or larger than before. Thank you for your support.
