### ISSUE TITLE
Week counter is wrong

### ISSUE THREAD

**Issue by Vecturia** [bluecaret/carettab#221]
Current week is wrong, it show that its 25 Week, but at real it is Week 24

**Comment by bluecaret** [comment]
This depends which format you are expecting. Please try the "ISO week" option. If you find this number is still incorrect please let me know. Thank you!

![image](https://user-images.githubusercontent.com/9217636/122606544-f1934b80-d02d-11eb-9fbc-be05e26adef4.png)
