### ISSUE TITLE
Feature Request: Prevent text selection on dynamic text elements.

### ISSUE THREAD

**Issue by TheSeg** [bluecaret/carettab#23]
On non-user interacted elements such as the clock and date, prevent selection of text.

Since the text changes programmability, it's useless to attempt to copy/paste anyway. Putting in a `user-select: none;` and perhaps a `cursor: pointer;` where applicable should fix things up.

**Comment by bluecaret** [comment]
Thanks, Although I believe there may be times you might want to select the date for a quick copy of it. But I'll look to see if there are any other areas that would be beneficial.

**Comment by TheSeg** [comment]
If that's a feature you want to implement, then selecting the date/time is broken. When the text updates each second or less, it breaks selection.

**Comment by bluecaret** [comment]
I have completed the work for this, it will go out with the next option. Text selection will be disabled by default and have an option within the "Extras" page to enable it.
