### ISSUE TITLE
Incorrect location

### ISSUE THREAD

**Issue by CberYellowstone** [bluecaret/carettab#233]
![image](https://user-images.githubusercontent.com/37031767/131175951-3545832b-e677-43ea-9237-b7fef3b99c44.png)

Everything’s in the upper left-hand corner

I tried to reset it, but it didn’t work

My version is 3.5.0 and I use the CentBrowser (Chromium 86.0.4240.198)

here is the console log

![image](https://user-images.githubusercontent.com/37031767/131176246-e0507aa9-d79e-4b8e-ad12-5bc909648b3f.png)

**Comment by bluecaret** [comment]
Hello, I'm sorry, there does seem to be an issue with the Cent browser specifically. I've had some others report this same thing. I believe it may be because I am using some CSS features the Cent browser may not support. I don't use the Cent browser myself and don't officially support the browser for CaretTab so there isn't much I can help with unfortunately. 

It is possible this was due to an issue with the weather widget though, which has been fixed. Try refreshing the new tab page next time you open it and see if it looks better or not.

If it continues to not work you can download version 3.4.1 from the following link and install it manually to get it back working again. There does seem to be a decent amount of people using the Cent browser though so I may consider looking into this further.

v3.4.1: https://drive.google.com/file/d/1CyUfGMB8QcGLMM2tl4JePeowccLKs81n/view?usp=sharing

**Comment by CberYellowstone** [comment]
> Hello, I'm sorry, there does seem to be an issue with the Cent browser specifically. I've had some others report this same thing. I believe it may be because I am using some CSS features the Cent browser may not support. I don't use the Cent browser myself and don't officially support the browser for CaretTab so there isn't much I can help with unfortunately.
> 
> It is possible this was due to an issue with the weather widget though, which has been fixed. Try refreshing the new tab page next time you open it and see if it looks better or not.
> 
> If it continues to not work you can download version 3.4.1 from the following link and install it manually to get it back working again. There does seem to be a decent amount of people using the Cent browser though so I may consider looking into this further.
> 
> v3.4.1: https://drive.google.com/file/d/1CyUfGMB8QcGLMM2tl4JePeowccLKs81n/view?usp=sharing

Maybe this is related to the old version of the Chromium 86.0.4240.198, not the specific CentBrowser

**Comment by bluecaret** [comment]
That's very possible, if that's the version that CentBrowser is using. Hopefully they update that soon. I am using some fairly new CSS methods with this latest version.

**Comment by CberYellowstone** [comment]
> That's very possible, if that's the version that CentBrowser is using. Hopefully they update that soon. I am using some fairly new CSS methods with this latest version.

because of the google's new law restricting limited 3rd-party Chromium bowser use google's sync api,
many 3rd-party Chromium broswer stay in Chromium 86 to keep sync func useable.
it seems that it is not possible to let a lot of 3rd-party Chromium browser update Chromium in a short time.
the proportion of users of the old version Chromium is still considerable,
so i think the best solution is to Use more compatible CSS methods.

**Comment by bluecaret** [comment]
Well that's unfortunate... Thank you for the information. I'll consider looking to see if there is anything I can do for this in the future. Thanks!

**Comment by bluecaret** [comment]
I've fixed this issue, keep a look out for the next update where it will be fixed :)

**Comment by CberYellowstone** [comment]
> I've fixed this issue, keep a look out for the next update where it will be fixed :)

How soon will it be updated on Google web store？

**Comment by bluecaret** [comment]
I'm planning on releasing a small update today, Chrome can take between 1-4 days for it to be made public. So hopefully by the end of this week it should be available.

**Comment by bluecaret** [comment]
This has been released in the latest version 3.6.0. The update went live in Chrome today.

**Comment by CberYellowstone** [comment]
> This has been released in the latest version 3.6.0. The update went live in Chrome today.

it seems that the location now works right...
but the backgrand color is still not work correctly.
just like this pic↓
![image](https://user-images.githubusercontent.com/37031767/134618326-6e2b6cc6-6e8a-4fdd-86d3-b214f87d0cd9.png)

**Comment by bluecaret** [comment]
Hmm that's odd. Please submit a new issue for this and I'll try to take a look into this soon.

Thanks
