### ISSUE TITLE
Backgroup picture shows blan when browser restart. Carettab version 3.5.0

### ISSUE THREAD

**Issue by Curious-r** [bluecaret/carettab#235]
Hi, it's still that old problem. Here are some general information:
Faulty page screenshot:
![image](https://user-images.githubusercontent.com/19733878/131332557-02a76392-96be-4bd8-abde-73d49cca1018.png)
Faulty page console screenshot:
![image](https://user-images.githubusercontent.com/19733878/131332875-8d44487a-336d-4662-bbd8-c75f3aab9e8b.png)
Normal page console screenshot:
![image](https://user-images.githubusercontent.com/19733878/131332997-8468699d-7abf-45e2-a211-4d1c6d51ec8d.png)

**Comment by Curious-r** [comment]
Hmmmm, what that mean? "prev 3.4.1, new 3.5.0"
![image](https://user-images.githubusercontent.com/19733878/131333559-b8d7337a-3e9b-4975-a5b7-892b63d3acda.png)
I'm already upgrade to 3.5.0 :
![image](https://user-images.githubusercontent.com/19733878/131333663-6a06da23-cedd-46d8-ad88-50f003fd000d.png)

**Comment by Curious-r** [comment]
And I tryed to reinstall the carettab, same problem is still exist. The screenshot of console after reinstall and configure is below:
![image](https://user-images.githubusercontent.com/19733878/131334063-8409b1bf-b43d-4fde-983e-1e25093b747b.png)

**Comment by bluecaret** [comment]
Thank you very much for the screenshots, very helpful! This bug seems to be haunting me :) I'll hopefully have time to look into this soon. I hope you'll be patient and wait for a fix.

The "prev 3.4.1, new 3.5.0" is just a note saying that the previous version you had installed was 3.4.1 and the current one is 3.5.0. Extension status above that would say "updated" if it detected that it was just updated.

**Comment by bluecaret** [comment]
Hopefully the latest update just released today, 3.6.0 should have fixed this but I can't be certain. Please let me know if you still experience the issue or not after you get the update. Thanks!

**Comment by Curious-r** [comment]
> Hopefully the latest update just released today, 3.6.0 should have fixed this but I can't be certain. Please let me know if you still experience the issue or not after you get the update. Thanks!

Well done, the problem is finally solved! I confirmed this after testing. Thank you for your efforts!

**Comment by bluecaret** [comment]
Really? Awesome! I was not confident in that fix so very happy to hear it did work! It does confirm a theory I had then. Thank you very much for further testing and letting me know!
