### ISSUE TITLE
Weather Widget: Offer 24-hour-clock setting for sunrise/sunset

### ISSUE THREAD

**Issue by hiergiltdiestfu** [bluecaret/carettab#238]
In the weather widget, I'd like to see the sunrise and sunset times in 24-hour format. 

I can imagine this to be a toggle in the widgets "General settings" section, maybe below the "Metric units" toggle, where most users from a non-imperial non-12h background would probably go looking. Maybe you can reuse the conversion logic from the Time widget.

I'm running CaretTab 3.5.0 on Chrome Version 93.0.4577.63 (Offizieller Build) (64-Bit)

Good work on the latest release, thank you!

**Comment by bluecaret** [comment]
Thanks for the suggestion!

**Comment by bluecaret** [comment]
This has been released in the latest version 3.6.0.

**Comment by hiergiltdiestfu** [comment]
@bluecaret Thanks, I was looking for it on release day b/c I think I saw it in the Release Notes, but I can't seem to find the setting for switching to 24h-format :(
