### ISSUE TITLE
Option to disable automatic display of "What's new" page after update

### ISSUE THREAD

**Issue by b2ag** [bluecaret/carettab#239]
I like Carettab but I dislike the big fat "What's new" page after each update. It annoys me enough by interrupting my flow that I will remove Carettab if it continues like this and I have no option to disable it.

**Comment by bluecaret** [comment]
I'm sorry if it causes trouble for you. My intention for it is to inform users of new features they may want to know about. I try to only display the full screen view of it when there are new features, if an update only has bug fixes I provide a subtler notice. In addition I always provide a method to dismiss the screen with a single click, to not disrupt users too much.

If yours is not behaving as I described above please let me know and I'll look more into alternative options.

I can look into just using a more subtle, non-disruptive way of notifying of new features as well in the future, and only save the full screen view for large scale updates or updates that cause a risk to settings.

Thank you for your feedback, it is very much appreciated!

**Comment by b2ag** [comment]
Yes I see the "single click dismiss button" and it works for me. Problem is I usually can't be bothered to click it right away. I do not open a new tab to click around in CarretTab that often. After some time I finally click it. Later I get annoyed again because I didn't yet also click it on my second PC. Multiply that by using firefox and chromium and the annoyance gets real.

**Comment by bluecaret** [comment]
Absolutely understand! I'll be giving this some good thought on how to inform about updates in a less intrusive way. Based on your last comments, sounds like a way to sync the dismissal of that screen as well so between machines you hopefully won't have to worry about it (though I can't do anything between browsers right now). Thank you again for the comments!

**Comment by b2ag** [comment]
I don't use browser sync options :(

**Comment by b2ag** [comment]
If the thing would vanish after ignoring it three times I guess I would be okay with it. Or you could change the options menu icon as the "what's new" section is already the first thing displayed there (also not a huge fan of that fact).

**Comment by b2ag** [comment]
I don't switch browsers that regularly. So not displaying it after a week or so if its not new ;) would be nice.

**Comment by bluecaret** [comment]
In v3.7.0 which should show up in the store soon, it changes the what's new section a lot, should be less intrusive and also dismissible now. And if you don't do anything with it after a week, it will automatically dismiss itself. Thank you.

**Comment by b2ag** [comment]
I choose to uninstall after the last updated which prompted for more permissions. So can't comment on this. :shrug:
