### ISSUE TITLE
Import settings forget   "patternId"

### ISSUE THREAD

**Issue by Moosh-be** [bluecaret/carettab#247]
I've  import my setting  from  browser to another, the pattern is lose

I see   "patternId": is  in json file so it's not an export problem

**Comment by bluecaret** [comment]
Thank you for the report, I'll take a look into it! 

If you are okay with it, do you mind posting your export here for debug purposes? You can remove any personal info like links.

**Comment by Moosh-be** [comment]
Ok  I can upload it  
But  I found my problem. 
as " new user" I've not read all notification.... And I think don't have refresh my page.

I just try again and pattern was successfully loaded in import.


`{
    "order": {
        "e": [],
        "items": [
            {
                "id": "SEARCH_1QUHAEPMFGX",
                "order": 1
            },
            {
                "id": "MESSAGE_1CUETHV7L63",
                "order": 2
            }
        ],
        "n": [],
        "ne": [
            {
                "id": "DATE_183AQFVON78",
                "order": 1
            }
        ],
        "nw": [
            {
                "id": "CLOCK_27OUNG1MDCW",
                "order": 1
            }
        ],
        "s": [],
        "se": [
            {
                "id": "COVID_3KE30S8BZCQ",
                "order": 1
            }
        ],
        "sw": [
            {
                "id": "WEATHER_KS096NVA56",
                "order": 1
            }
        ],
        "w": []
    },
    "design": {
        "background": "#0000FF",
        "brightness": 10,
        "colorsId": 0,
        "customFont": "Comic Sans MS",
        "customFontWeight": 40,
        "font": 181,
        "foreground": "#ffff00",
        "hideLogo": true,
        "hideMenu": false,
        "imageBlend": 10,
        "imageSize": 10,
        "patternId": 4000,
        "scaling": 8,
        "scalingMethod": true
    },
    "messages": {
        "enabled": true,
        "id": "MESSAGE_1CUETHV7L63",
        "marginHeight": 0,
        "marginWidth": 2,
        "messageList": [
            {
                "id": "MESSAGETEXT_1PCCEZ3K991",
                "text": "Hello world!"
            }
        ],
        "offset": 0,
        "position": "c",
        "random": true,
        "scaling": 8,
        "textAlign": "center",
        "width": 100
    },
    "i18n": {
        "lang": "fr-FR"
    },
    "bookmark": {
        "apps": true,
        "bookmarksManager": true,
        "chromeTab": true,
        "enabled": true,
        "history": true,
        "icons": true,
        "mostVisited": false
    },
    "quickLink": {
        "apps": false,
        "bookmarksManager": false,
        "chromeTab": false,
        "enabled": true,
        "history": false,
        "icons": true,
        "id": "QUICKLINK_C5HDR1KCPMG",
        "links": [
            {
                "id": "LINK_2OKQ6AXD3ZW",
                "label": "Google",
                "url": "https://www.google.com/"
            },
            {
                "id": "LINK_1EXP1722D1K",
                "label": "Intranet",
                "url": "xxxxxxxxx"
            }
        ],
        "marginHeight": 3,
        "marginWidth": 2,
        "mostVisited": false,
        "offset": 0,
        "padding": 5,
        "position": "n",
        "scaling": 7,
        "textAlign": "center",
        "vertical": false,
        "width": 100
    },
    "time": {
        "clocks": [
            {
                "analog": {
                    "enabled": false,
                    "style": 10
                },
                "binary": {
                    "dim": false,
                    "enabled": false
                },
                "brackets": {
                    "dim": false,
                    "enabled": false,
                    "left": "[",
                    "offset": 0,
                    "padding": 1,
                    "right": "]",
                    "scaling": 10
                },
                "delimiter": {
                    "blink": false,
                    "dim": true,
                    "enabled": true,
                    "offset": 0,
                    "scaling": 10,
                    "symbol": ":"
                },
                "id": "CLOCK_27OUNG1MDCW",
                "label": {
                    "dim": false,
                    "enabled": false,
                    "offset": 0,
                    "scaling": 10,
                    "text": "Main clock"
                },
                "marginHeight": 0,
                "marginWidth": 0,
                "meridiem": {
                    "am": "am",
                    "dim": false,
                    "enabled": false,
                    "offset": 0,
                    "pm": "pm",
                    "scaling": 10
                },
                "offset": 0,
                "padding": 10,
                "position": "nw",
                "relativeTime": {
                    "dim": false,
                    "enabled": false,
                    "offset": 0,
                    "scaling": 10
                },
                "scaling": 10,
                "seconds": {
                    "dim": false,
                    "enabled": true,
                    "offset": 0,
                    "scaling": 20
                },
                "span": 40,
                "timezone": "Automatic",
                "twentyFour": true,
                "twoDigit": false
            }
        ]
    },
    "covidData": {
        "countries": [
            {
                "code": "BE",
                "enableActive": true,
                "enableCountryName": false,
                "enableDeaths": true,
                "enableFlag": true,
                "enablePer1M": false,
                "enableRecovered": false,
                "enableToday": true,
                "flagImage": "https://disease.sh/assets/img/flags/be.png",
                "id": "COVID_3KE30S8BZCQ",
                "marginHeight": 5,
                "marginWidth": 4,
                "name": "default",
                "offset": -46,
                "padding": 10,
                "position": "se",
                "textScaling": 8,
                "width": 100
            }
        ],
        "enabled": true
    },
    "date": {
        "day": {
            "enabled": true,
            "twoDigit": false
        },
        "dayOfWeek": {
            "abbr": false,
            "enabled": true
        },
        "dimDelimiter": false,
        "enabled": true,
        "format": 20,
        "id": "DATE_183AQFVON78",
        "marginHeight": 0,
        "marginWidth": 10,
        "month": {
            "abbr": false,
            "enabled": true,
            "twoDigit": false
        },
        "offset": 0,
        "position": "ne",
        "scaling": 6,
        "short": {
            "delimiter": "/",
            "enabled": false
        },
        "timezone": "Automatic",
        "week": {
            "enabled": false,
            "iso": false,
            "label": "Week",
            "offset": 0,
            "scaling": 10
        },
        "year": {
            "enabled": true,
            "twoDigit": false
        }
    },
    "search": {
        "autocomplete": true,
        "enabled": true,
        "engine": 10,
        "id": "SEARCH_1QUHAEPMFGX",
        "label": "Recherche sur google",
        "marginHeight": 0,
        "marginWidth": 10,
        "offset": 0,
        "position": "c",
        "scaling": 4,
        "width": 21
    },
    "weather": {
        "celsius": true,
        "current": {
            "astro": {
                "moonPhase": false,
                "sunrise": false,
                "sunset": false
            },
            "enabled": true,
            "humidity": {
                "enabled": true
            },
            "icon": {
                "enabled": false,
                "size": 1
            },
            "pressure": {
                "enabled": false
            },
            "temp": {
                "currently": true,
                "degree": true,
                "feelsLike": false
            },
            "wind": {
                "enabled": true
            }
        },
        "enabled": true,
        "forecast": {
            "day": {
                "enabled": true
            },
            "days": 2,
            "enabled": true,
            "hideToday": false,
            "horizontal": true,
            "icon": {
                "enabled": false,
                "size": 1
            },
            "temp": {
                "degree": true,
                "high": true,
                "low": false
            }
        },
        "id": "WEATHER_KS096NVA56",
        "location": {
            "url": "soignies-belgium"
        },
        "marginHeight": 2,
        "marginWidth": 4,
        "metric": true,
        "offset": 0,
        "padding": 5,
        "position": "sw",
        "preciseDigits": false,
        "scaling": 12,
        "twentyFour": true,
        "windUnits": false
    },
    "misc": {
        "disableSelect": true,
        "enableAnalytics": true,
        "schema": "1.1",
        "title": {
            "clockUsed": 1,
            "text": "Hello world!",
            "type": 10
        }
    }
}`
