### ISSUE TITLE
More custom links?

### ISSUE THREAD

**Issue by karambaq** [bluecaret/carettab#25]
Will it be available?

**Comment by bluecaret** [comment]
Hello, yes this is something that is planned for a future release. I haven't been able to commit anytime to the extension lately though but hoping to get some more features made this winter. Thank you.

**Comment by Alexmarch1** [comment]
I also do not have enough More custom links

**Comment by karambaq** [comment]
Please, I need  it sooo much. Maybe it will be the same 6 labels but it will be droplist with the links inside?

**Comment by bluecaret** [comment]
Question for all interested in more links... 
Would you prefer unlimited links, managed in the same way it is now OR integration with the bookmarks in your browser? OR an option to toggle between the two methods

I can see maybe wanting these shortcuts separate from your actual bookmarks especially if you are already showing the bookmarks bar all the time.

**Comment by karambaq** [comment]
@bluecaret Shortcuts to toggle sublinks would be great I think. Sorry if I got you wrong, my english is not so good.

**Comment by bluecaret** [comment]
Hey all, just updated to v2.3.1 on both chrome and firefox. With this update you can now add an unlimited number of links! Enjoy!

I may add functionality to incorporate the links into the browser's bookmarks at a later date.

**Comment by karambaq** [comment]
Thamk you so much!
