### ISSUE TITLE
options.common.down and options.common.up never used

### ISSUE THREAD

**Issue by Moosh-be** [bluecaret/carettab#252]
I've search for options.common.down and options.common.up 
Nowhere I found this calls 

but in I18n  there  are  .up and .down in common section

**Comment by bluecaret** [comment]
Thank you. I believe these may not be used anymore. I'm sure there are more that are no longer used as well, the translations could use some cleanup in this regard, though at the same time for these common ones it is good to have on hand in case I need it again in the future :)

**Comment by Moosh-be** [comment]
Hum..
IMHO => KISS principle => If  you don't need now, clean your code, git is your friend when need is back ;)

If you agree I can try too identify more "unused"  translation to remove or comment them

**Comment by bluecaret** [comment]
I'd be happy to accept a PR for some cleanup :)
