### ISSUE TITLE
most visited not very readable with  edge dark mode ;)

### ISSUE THREAD

**Issue by Moosh-be** [bluecaret/carettab#255]
Default mode (sorry my  interface is in french) it's alright
![image](https://user-images.githubusercontent.com/388085/140935531-3366737a-ae70-4c9c-8afb-f358d23782d4.png)

![image](https://user-images.githubusercontent.com/388085/140935594-9f253baf-6102-4c4c-abb1-22e9d997cfd6.png)

but if I switch to  dark mode (mode sombre/foncé)
![image](https://user-images.githubusercontent.com/388085/140935737-d73c528e-4026-49ba-9eba-ad1b975f19e1.png)

oops
![image](https://user-images.githubusercontent.com/388085/140935794-34b6d11d-d8fd-4665-8bda-fe08aaff1145.png)

**Comment by CalciumC** [comment]
in chrome too. it's almost unusable.

**Comment by bluecaret** [comment]
Thank you! This has been fixed and will be in the next update.

**Comment by bluecaret** [comment]
Version 3.6.4 has been published to the Chrome Web Store. Keep a look out for it within a couple days.
