### ISSUE TITLE
Lack of timezones

### ISSUE THREAD

**Issue by spidamoo** [bluecaret/carettab#26]
Hey guys!
There is only a selected subset of timezones available in the settings and I can perfectly understand the reason behind it — to make the list not too polluted. But as a matter of fact this solution does not really work :)
For example I want to use +11 timezone to see the time in Sakhalin on one of my additional clocks but it's not possible: Asia/Magadan (+11) shows the same time as Pacific/Guam (+10). Because of DST I believe.
So I could implement a fix myself and merge-request it. The only thing is I'm not sure what would be an appropriate approach here. I could just add Asia/Sakhalin timezone to the list and that would resolve my issue but won't help if somebody else has a similar issue in the future. On the other hand adding all possible timezones would interfere with the simplicity philosophy of the extension :) So what do you guys think?

**Comment by spidamoo** [comment]
I've just tried to use timezone  Asia/Sakhalin and it does not show the correct time anyways :(
For example I can either have +11 timezone showing that the time is 21:10 or +12 showing 23:10. While in reality the time there is 22:10.
Maybe it's something about moment library that does not handle the timezones correctly? I'll try to investigate this further...

**Comment by spidamoo** [comment]
... it did not take me to really dig deep into this to find a solution. Apparently the guys who maintain moment.timezone do great job following all the changes in new rules introduced about how DST should be in different zones so updating the 2010 version to 2012 one did the trick.

**Comment by bluecaret** [comment]
Awesome! Thank you for the effort, I'll make sure to get this in to the next update. Unfortunately I haven't had time of late to even open my code editor so it might be a little while, but I greatly appreciate the help! Timezones are, let's face it,, annoying. And yes at first I had the full list of them until I realized how unwieldy it was so tried to go with the bare bones that covers each time increment, for the most part anyway.

**Comment by spidamoo** [comment]
I figured I better point out that maybe you did not actually notice that I also made a pull request regarding this issue so you don't really have to open a code editor to fix it ;)

**Comment by bluecaret** [comment]
Hi, thanks yes I saw that, really appreciate it! I still have to up the version number, and update my changelog in the app and on my site, and then upload it to the store. I swear I will get there soon though! :)

**Comment by bluecaret** [comment]
Okay you got me off my butt, updating the extension tonight :)
