### ISSUE TITLE
When "most visited" is enabled by config import but not already authorized, I have an "not working link"

### ISSUE THREAD

**Issue by Moosh-be** [bluecaret/carettab#262]
It's just an idea.

When "most visited" is enabled by config import but not already authorized,
![image](https://user-images.githubusercontent.com/388085/146807870-154b8791-369b-48cd-8201-779b7228ab2b.png)
I have an "not working link"

The idea is to let open a box with same message than message in settings.
![image](https://user-images.githubusercontent.com/388085/146807610-860f03ca-c8b7-4e61-adbc-76911cc858cb.png)

**Comment by bluecaret** [comment]
Thank you for finding this bug, I'll look into getting this fixed.

**Comment by Moosh-be** [comment]
and  what  did you think about idea? 
> The idea is to let open a box with same message than message in settings.

**Comment by bluecaret** [comment]
Sorry for the unreasonably long delay in response... Your suggestion is actually how it **should** be working, that's what I meant when I said it was a bug. Thank you!

**Comment by bluecaret** [comment]
This is fixed and will be in the next update. Now when importing your settings, if you haven't already allowed the extra permissions, it should ask you for them during the import.

**Comment by bluecaret** [comment]
Version 3.6.4 has been published to the Chrome Web Store. Keep a look out for it within a couple days.
