### ISSUE TITLE
Clocks in a row?

### ISSUE THREAD

**Issue by sergiizaskaleta** [bluecaret/carettab#263]
Question/possible regression issue:

A few versions back I was able to arrange additional clocks in a row below the primary clock.

In the current version (3.6.2) it seems that inside a single "position" area all clocks will be aligned vertically.

Is there any way for me to arrange clocks horizontally in a row?

I'm looking for this layout (but with "main" clock centered):

|&nbsp;\||&nbsp;|\|&nbsp;|
|---|---|---|
|&nbsp;\||<p style="text-align: center;">main clock<br>extra clock1 .. extra clock2 .. extra clock3</p>|\|&nbsp;|
|&nbsp;\|| |\|&nbsp;|

**Comment by bluecaret** [comment]
Hello, yes I had to adjust the way some default settings are to accommodate the extra positions widgets can be placed at. You can still accomplish what you want however with some small adjustments.

In the settings for each clock is a "width" option under the Layout section, if you set the main clock to 100% width, and the extra clocks to a smaller amount, you should get the desired result. Below you'll see I have a main clock at 100% and two additional clocks each set to 25%.

![image](https://user-images.githubusercontent.com/9217636/148082438-27e38cff-d91a-4c7f-b80b-f6a187ab3fc0.png)
![image](https://user-images.githubusercontent.com/9217636/148082479-a75a2ec7-1f82-4739-a6ef-c92280c308d0.png)

Thank you for using CaretTab! Feel free to respond if you're still seeing issues.

**Comment by sergiizaskaleta** [comment]
Resolved! <3
