### ISSUE TITLE
quick link update screws up the settings

### ISSUE THREAD

**Issue by libralibra** [bluecaret/carettab#266]
recently, one of my bookmark websites changed its URL from .com to .tv. As long as I updated this in the quick link section and saved it, the setting is not accessible anymore. The information was not parsed properly and I have nowhere to change it at all.

the setting won't pop up no matter how many times I clicked the bottom right corner icon. I tried to uninstall and install the carettab add on and there is no luck. It looks like there are some leftovers even after I uninstall it from Firefox.

After I looked the log, it looks like there must be some js code that doesn't like .tv URL, which is very common nowadays. The error message is pasted below:

**ERROR TypeError: URL constructor: www.***.tv is not a valid URL.                        main-es2017.js:2:646514**

Environment: Windows 10 Enterprise
Browser: Firefox 97.0 (64 bit)

Forgot to mention: the same link worked in MS Edge browser. The difference between the Edge and FIrefox, if I can remember, **may** be:

In Edge, I put 'https://www.***.tv'. But in Firefox I put 'www.***.tv' without https:// prefix. Is that difference the reason for this issue?

**Comment by libralibra** [comment]
is there any way that I can modify the links directly to fix the problem temporarily?

tried to locate the file but failed to get one from the firefox profile folder.

**Comment by bluecaret** [comment]
You need to have the https:// part on your URL, it will not work otherwise. In Firefox make sure to add it with that part.
