### ISSUE TITLE
Missing the translation of `Feels like`

### ISSUE THREAD

**Issue by lhyUnited** [bluecaret/carettab#270]
Hi 👋 , just found out it always shows `Feels like` no matter what language applied.

https://github.com/bluecaret/carettab/blob/683b4280d80588b89b14780e88069bc403cd060b/src/app/tab/weather/weather.component.html#L41

**Comment by bluecaret** [comment]
Thank you! This has been fixed and will be in the next update.

**Comment by bluecaret** [comment]
Version 3.6.4 has been published to the Chrome Web Store. Keep a look out for it within a couple days.

**Comment by lhyUnited** [comment]
Looks great. Thanks for the update!
