### ISSUE TITLE
Firefox 'privacy.resistFingerprinting' breaks custom fonts

### ISSUE THREAD

**Issue by sxdjt** [bluecaret/carettab#274]
Enabling privacy.resistFingerprinting in Firefox breaks the use of custom fonts in Caret Tab.

Repro steps:

1. Open about:config
2. Enable 'privacy.resistFingerprinting'
3. Open a new Caret Tab with a custom font

MacOS 12.4
Firefox 100.0.2
Caret Tab: 3.6.2

**Fingerprinting on**
<img width="1160" alt="Fingerprinting-on" src="https://user-images.githubusercontent.com/53812540/169911554-bb3dfe61-501f-4469-8447-86ae19decb47.png">

**Fingerprinting off**
<img width="1165" alt="Fingerprinting-off" src="https://user-images.githubusercontent.com/53812540/169911556-cd2fdb49-26c3-4021-a96b-4e7a67e6bae3.png">

**Comment by bluecaret** [comment]
My apologies. I've pulled CaretTab from Firefox. I could not justify continued development there with the amount of users I had. Maybe in the future I can reconsider, but right now I just don't have the time.

I hope you continue using CaretTab on Chromium browsers.

**Comment by sxdjt** [comment]
No worries, thanks for the update.  I am committed to Firefox, so I'll be sure to archive a copy of 3.6.1 for my future needs.
