### ISSUE TITLE
RFE: Category trees for Quick Links

### ISSUE THREAD

**Issue by Comnenus** [bluecaret/carettab#277]
I love quick links, and would like to organize them in a collapse/expand tree format.

**Comment by StewAlexander-com** [comment]
Hi @Comnenus  -

That's a file manager, try downloading and using [ranger](https://github.com/ranger/ranger), highly configurable and fun to use

Or

[nnn](https://github.com/jarun/nnn) if you don't want as many options

**Comment by StewAlexander-com** [comment]
@Comnenus if you use Windows try [lf](https://github.com/gokcehan/lf) - the easiest way to install it is by using the Chocolatey WIndows package manager with the instructions ```choco install lf -y```

**Comment by bluecaret** [comment]
Thank you for the suggestion. Quick links are meant to be just that, quick. An organized, nested structure like that should be reserved for the bookmarks bar.
