### ISSUE TITLE
Feature Request:  Option to connect your calendar

### ISSUE THREAD

**Issue by tarunvijwani** [bluecaret/carettab#278]
I would really appreciate it if you can add the option to connect the calendar and display Today's meetings in a tab.

**Comment by StewAlexander-com** [comment]
Hi @tarunvijwani -

Just a heads up there are other tab managers that already do this [Momentum New Tab Extension](https://chrome.google.com/webstore/detail/momentum/laookkfknpbbblfpciffpaejjkokdgca)

Not sure we need to reinvent the wheel and essentially duplicate other new tab managers - what this does is great, and it's minimalistic more so than [Minimalist](https://chrome.google.com/webstore/detail/minimalist-new-tab/cadppknnfehhlmfdkemdmdoogcldmane) which I and I think other users like

**Comment by bluecaret** [comment]
I do not plan on adding calendar integration at this time. That in particular would bloat the extension a lot, and as @StewAlexander-com so nicely put it, I try to keep this minimalistic. Maybe in the future I'll consider some sort of basic implementation, but don't wait on it.
