### ISSUE TITLE
Custom font option

### ISSUE THREAD

**Issue by Martin1887** [bluecaret/carettab#28]
Hello.

Firstly, thanks for this great addon.

Secondly, it would be great an option for custom font (similar to custom message). I think it is easy to implement, so the 'style="font-family: '{custom-font}' !important" can be appended to the body instead using a class in the body for the font.

Regards.

**Comment by bluecaret** [comment]
Thanks for the suggestion, great idea!

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
