### ISSUE TITLE
Pressing the search button returns undefined

### ISSUE THREAD

**Issue by thechantaro** [bluecaret/carettab#282]
Hi,

This is a low priority slight annoyance, but when the search button is clicked without any text (Search Box) the set search engine starts a search for the term "undefined".
Would it be possible to make the button not do anything when nothing is typed?

Kind Regards
Chantaro

**Comment by bluecaret** [comment]
I've fixed this issue, expect to see it in the next update. Thank you!

**Comment by bluecaret** [comment]
Version 3.6.4 has been published to the Chrome Web Store. Keep a look out for it within a couple days.

**Comment by thechantaro** [comment]
Well too bad I use firefox... --Sent from my Android phone with GMX Mail. Please excuse my brevity.On 11/4/22, 04:49 John Hancock ***@***.***> wrote:

   
  Version 3.6.4 has been published to the Chrome Web Store. Keep a look out for it within a couple days.
