### ISSUE TITLE
Increase performance on tab open

### ISSUE THREAD

**Issue by Martin1887** [bluecaret/carettab#29]
I have noticed a roughly second lag when a new tab is open using htis addon in Firefox 57, it would be great if the load time could be reduced.

I have seen in developer tools that there are several LESS files and I wonder if they are compiled when a new tab is open. If this is the case, compiling the LESS files when options are changed instead on new tab open could incrase notably the performance I think.

Thanks and regards.

**Comment by bluecaret** [comment]
Yes there is a bit of delay... I will need to do extra research into that, not sure what would be causing it. Although this may be a problem with Chrome as well but is just more prominent within Firefox due to the progress bar within the tab that shows making it more obvious (to me anyway).

The LESS files are actually compiled when I develop it, not when loaded, and I unnecessarily include the files in the extension (I have a lot of cleanup and general improvements to do).

Thanks!

**Comment by bluecaret** [comment]
@Martin1887 Do you still notice a delay? I have changed to using SASS and only including the compiled code instead, I haven't done anything else specifically for this though but just want to see if you are still noticing the delay?

**Comment by Martin1887** [comment]
I have not notice any improvement.

The delay is specially noticeable and annoying if you configure a dark background, so a white flash is shown until CaretTab is completely loaded.

I have also noticed that sometimes the menu is opened and fastly closed, maybe some improvement could be got delaying the configuration menu load with a setTimeout or a similar thing.

Thanks for working on the issue!

**Comment by bluecaret** [comment]
Thank you for the extra information. Unfortunately I'm not sure there is anything I can do about the flash of white as it loads other than to suggest making sure animations are on so it fades in. Other extensions have this same issue and is just a side effect of having to load code.

However I will try to do what I can to hopefully minimize the delay the best I can.

As far as the menu showing for a bit on load, yes this is something I have noticed as well in certain times, I'm looking into that one.

Thank you!

**Comment by gsbabil** [comment]
Hi @bluecaret, @Martin1887,

I confirm the delay on Firefox 57 as well.

I'm currently on Firefox 58.0b10, and I have noticed that sometimes
when opening a new tab, there's a brief animation as if the
caret-tab side-bar options pane (on the right-hand side) is
transitioning out.

The animation is almost the reverse animation of when the caret-tab
side-bar options button clicked, and the options pane transitions
in. This might also be the reason for the ~1sec delay in question.

Ideally, when a new Firefox/Chrome tab is opened, there should be
minimum delay in displaying the default screen with time/date etc.

Hope this helps. Thanks a lot.

**Comment by bluecaret** [comment]
Hello, thanks for the details. I'm currently working on a complete rewrite of the extension code that I hope will improve performance a lot and minimize the delay. It will definitely fix that animation bug. Might take a while for me to get it out though, day job and all, so please be patient but it is in the works. Thank you again, I appreciate all feedback!

**Comment by gsbabil** [comment]
Hey @bluecaret,

Thanks for the prompt update, and your wonderful add-on. Will
certainly look forward to your next update! Thank you.

**Comment by bluecaret** [comment]
Hi, just wanted to give an update to this. I'm currently rewriting the extension from scratch right now, and early indications are showing a big increase in performance on load! As long as that continues to be true I think this should be resolved in the next update. But please be patient, it is a big update and will be a while yet before I can release it.

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
