### ISSUE TITLE
Search box shortcut

### ISSUE THREAD

**Issue by JoeABCDEF** [bluecaret/carettab#300]
Is it possible to add shortcuts to the input box, Quick focus, or When autofocus for the first time

**Comment by bluecaret** [comment]
Chrome does not allow auto focusing on an input by default, but I can look into adding a key combination shortcut that can move the cursor to the search box.

**Comment by JoeABCDEF** [comment]
Thanks for the trouble to add a shortcut, thanks! @bluecaret

**Comment by bluecaret** [comment]
Hello, I'm sorry to say that I was not able to get this working. The browser really forces the address bar to be in focus. Even setting up a shortcut did not work. I'm afraid I won't be able to implement this.
