### ISSUE TITLE
[Feature Request] Binary Clock Digits

### ISSUE THREAD

**Issue by MrDiamondDog** [bluecaret/carettab#304]
Just a small feature to allow the binary clock to show digits instead of dots.

**Comment by bluecaret** [comment]
Thanks for the suggestion! To be clear, by digits do you mean like 1's and 0's or a legend to show what the dots represent?

**Comment by MrDiamondDog** [comment]
1's and 0's

**Comment by Ruandv** [comment]
@bluecaret I'd like to take on this small enhancement. 
Will it be ok if I make use of the :before pseudo element and then just set the text inside of the "dot"?

**Comment by bluecaret** [comment]
@Ruandv Yes I think that would be the best approach. However, something to consider: In the spirit of the extension, I would like to leave the "1" and "0" to be customized by the user, so if they choose to use numbers it will default to those, but they can change it if they want. Therefore I wouldn't want to hardcode the numbers in the CSS. That being said, you could use data attributes in the html to apply the user's option and then access that in the CSS with `content: "attr(data-binary-on)"`

Thank you for the help!

**Comment by bluecaret** [comment]
Released in version 3.7.0 which will be available in the web store soon.
