### ISSUE TITLE
Weather Location

### ISSUE THREAD

**Issue by Zahaag** [bluecaret/carettab#306]
Hi, I have a problem cuz I can't put my location on the weather. The problem is that the acceptation panel "**SELECT YOUR LOCATION**" doesn't appear. I checked the logs:
When **Weather Search API** response **show 1 option**, the panel is closed and can't accept, but the search is good (checked lat and lon), _it only appear when it **found 2 or more options**._ So even when it found good location you can't accept it cuz you don't have how. 
I don't know if it a error from www.weatherapi.com or someone put the showlist conditions as 2 or more.

**Comment by bluecaret** [comment]
Hi, what version of CaretTab are you on? You can check by looking at the bottom of the settings panel. I recently pushed an update that I believe fixes the issue you are seeing. You should be looking for version 3.6.4

If you are already on this version let me know and I'll look into this.

**Comment by Zahaag** [comment]
I have a Version 3.6.4 and I am using chrome

**Comment by bluecaret** [comment]
Hi, sorry for the delay. I'm trying to look into this but am not seeing the same issue. Can you let me know what location you are searching for? If you don't want to put that in this public place you can email me at bluecaret@outlook.com. If you could also include a screenshot of the logs and the page after you click the search button? Thank you.

**Comment by bluecaret** [comment]
My apologies. I have been able to reproduce this now and will try to get a bug fix in quickly. I thought I had fixed this already so not sure why it is still happening but it should be quick (given the time it takes for the store to release updates which can be a few days). In the meantime if you like you can send me an export of your settings to bluecaret@outlook.com and I can adjust your settings to force the location in, also make sure to send me the location you are searching. 

Or, it sounds like you might be capable of it yourself. If you look at the console logs when you perform a location search, open the object that shows with the "weather search api response" log, in there will be a string for "url" of the location you want, if you copy that and add it to the "weather.location.url" setting within your settings export, then reimport that back in you should be set.

**Comment by bluecaret** [comment]
Published an update that should fix this. Chrome usually takes a few days to get the update out. Thank you for reporting the bug!
