### ISSUE TITLE
[Feature Request] Notes

### ISSUE THREAD

**Issue by ErnestasMitkus** [bluecaret/carettab#307]
Could we get something like a notes/todo list? Preferably with each note as a separate entity which could be clicked on to be marked as done.

**Comment by bluecaret** [comment]
On the list, and working on it now actually :) To start it might just be a notepad type feature for just a single large note area, and later may add a To Do list option.

**Comment by bluecaret** [comment]
I am still planning a to-do list widget, but a notepad widget has just been added in v3.7.0 which will be out on the store soon.
