### ISSUE TITLE
[BUG] Week numbering is one off

### ISSUE THREAD

**Issue by ZachTheDev** [bluecaret/carettab#309]
Today (12/26) the week number says it is Week 53. According to my knowledge, and this [website](https://www.epoch101.com/week-numbers-2022), there are only 52 weeks and today should be the start of week 52.

**Comment by Ruandv** [comment]
@ZachTheDev by enabling the ISO week number option this will correctly display the week number. 
![image](https://user-images.githubusercontent.com/2345436/209574086-b1fb0a06-ac82-4c6e-ba46-1d35c481bd10.png)

**Comment by ZachTheDev** [comment]
Thanks! I just found that. Is this just an odd year where there happens to be 53 Sundays? Or why might the default (non-ISO format) think there is 53 weeks? Thanks!

**Comment by Ruandv** [comment]
It depends on which day is set as the first day of the week.

**Comment by bluecaret** [comment]
Thanks for the message, @Ruandv is correct, the default goes based on what day the first of the year lands on. 

Thanks for the help answering @Ruandv.
