### ISSUE TITLE
[BUG Report] Background picture shows blank again in version 3.7.0

### ISSUE THREAD

**Issue by Curious-r** [bluecaret/carettab#311]
Browser version: Edge 109
Screenshots:
![image](https://user-images.githubusercontent.com/19733878/213411487-b1514fe8-2eb7-43d3-8c8f-b2004d17533d.png)
![image](https://user-images.githubusercontent.com/19733878/213411628-49116909-6ef8-4f1c-b6e8-46f4368a7269.png)
![image](https://user-images.githubusercontent.com/19733878/213411896-a6c0c3df-03a3-494e-b603-e8741e76237c.png)

**Comment by bluecaret** [comment]
Thank you for reporting. The recent update changed a bit on how the background images are saved, and I unfortunately messed up the migration from the old way to the new way, which is probably why you see it blank. Can you please try changing to a different pattern, save, then change it back and save. This should resolve it.

If that doesn't work, it's possible the brightness level might be too high for that pattern. With a solid white background, and that particular pattern, anything above brightness 10 will look solid white. Try changing the brightness lower.

![image](https://user-images.githubusercontent.com/9217636/213583033-ff597a2a-6652-4075-ba93-e32961199aa9.png)

Thank you

**Comment by Curious-r** [comment]
> Thank you for reporting. The recent update changed a bit on how the background images are saved, and I unfortunately messed up the migration from the old way to the new way, which is probably why you see it blank. Can you please try changing to a different pattern, save, then change it back and save. This should resolve it.
> 
> If that doesn't work, it's possible the brightness level might be too high for that pattern. With a solid white background, and that particular pattern, anything above brightness 10 will look solid white. Try changing the brightness lower.
> 
> ![image](https://user-images.githubusercontent.com/9217636/213583033-ff597a2a-6652-4075-ba93-e32961199aa9.png)
> 
> Thank you

After repeatedly modifying and saving several times, the wallpaper can be displayed normally. Thanks!
