### ISSUE TITLE
Feature Request: Custom Search Engine

### ISSUE THREAD

**Issue by schroenki** [bluecaret/carettab#312]
I would like to have the option to define my own search engine for the search bar, not just use the preset ones. I believe this could be implemented by allowing the user to enter / paste an URL with a placeholder like %s for the search term. 
Thank you for considering my request!

**Comment by bluecaret** [comment]
Hello, the latest update, v3.8.0 that just released this week includes this feature as a Premium Access feature. If you'd like to sign up for Premium, it costs only $2 a month and can be subscribed to from within the settings panel of the extension.

Thank you!
