### ISSUE TITLE
Can't save background properly using large pictures

### ISSUE THREAD

**Issue by FluoK** [bluecaret/carettab#313]
Broswer version: Edge 109
Can save using images less than about 4MB, but cannot while >4MB
![msedge_GvNmse48vQ](https://user-images.githubusercontent.com/31159557/216924496-7413f6c4-8e86-4db0-80e0-c0a2507a95b5.gif)

**Comment by FluoK** [comment]
#311 Have tried this but didn't work

**Comment by bluecaret** [comment]
It seems that the file size warning is not working correctly. There is a limit on how large the images can be as it saves in the browser's storage and the browser adds limits to that. I'll make sure that file size warning gets added back in.

Thank you for reporting!

**Comment by bluecaret** [comment]
This bug has been resolved and will be seen in the next update. Thank you!
