### ISSUE TITLE
Feature request: Quarter offsets

### ISSUE THREAD

**Issue by davidAlittle** [bluecaret/carettab#315]
In the calendar widget, there is the option to show which quarter it currently is. The 'natural' (calendar) quarter is helpful, but for almost every business the fiscal year 'quarter' is often numbered differently. 

Don't know about others, but I need to figure out what fiscal year quarter it is often, but calendar year quarter almost never. 

Would it be possible to add an option for either an offset to the quarter? (the ability to show the offset, like there is with the clocks, would be nice too).

**Comment by bluecaret** [comment]
Thank you for the suggestion! Do you think just an offset in months would be good enough? I'm not sure if businesses ever put there fiscal year in the middle of the month, I'm guessing not. Month offset would certainly be the most reliable.

**Comment by davidAlittle** [comment]
I think you're right, 99% of use cases would be a quarterly offset, but since a monthly offset would cover _all_ use cases, and it's simple enough to pick '3 months' vs '1 quarter', I'd agree that a month offset is the simplest way to handle it.

Thanks!

**Comment by davidAlittle** [comment]
You're using Moment.js, right? Maybe this is enough? https://momentjscom.readthedocs.io/en/latest/moment/10-plugins/13-fquarter/

**Comment by bluecaret** [comment]
Ya that would probably do it. I'll get this in an update soon. Thanks!

**Comment by bluecaret** [comment]
Got this done, it should appear in the next update, hoping to get that out in the next few days.
