### ISSUE TITLE
Most used links

### ISSUE THREAD

**Issue by deejay253** [bluecaret/carettab#4]
Is it possible for the links to be the top 6 used websites?

**Comment by bluecaret** [comment]
Still considering this. Trying to keep the size of the extension and the amount of resources minimal as well as permissions. I'm unclear at the moment whether this would affect that or not. Will look into it later on however. Thanks for the support!

**Comment by deejay253** [comment]
This should be a low priority item, as there is the ability to add favorites. This should hold me over :)

**Comment by kostyanx** [comment]
I want too this feature. Six links too few. May be make responsible design? If more links added set text smaller or add new line for links? or ex. if 7 links added, set in first line 4 and second line 3

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
