### ISSUE TITLE
clear the search history?

### ISSUE THREAD

**Issue by wondor** [bluecaret/carettab#43]
The carettab is very impressive and I love it, the only problem is that I cannot find the button to clear the search history.I hope that the carettab can get better.

**Comment by bluecaret** [comment]
I'm not doing anything specific to save that information, it is just what the browser remembers so clearing out browsing data from Chrome's settings might clear it out. However, I'll look into possibly adding a button to clear it out. Thank you.

**Comment by ImJoyed** [comment]
I meet the same problem to and have a solvtion. You can add an "autocomplete" property to "input" label like this: <form autocomplete="off" id="search" class="fadein" method="get" action="https://www.google.com/search">

**Comment by bluecaret** [comment]
Thanks! I can add a toggle for that in settings. Won't be able to clear them out to start fresh but can at least keep it from providing suggestions. I'll get that added to a future release.

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
