### ISSUE TITLE
Settings doesn't open on firefox 57

### ISSUE THREAD

**Issue by RX14** [bluecaret/carettab#44]
I can't see what i'm doing wrong, but I've clicked on pretty much everywehre on the new tab page including the caret and nothing happens. I can get it to show by changing the CSS on `#config` by hand, but this is clearly not ideal.

**Comment by bluecaret** [comment]
Hi, sorry for the trouble. Are you on a Mac or PC? I've had a similar report recently about this on a Mac.

Also can you take a look at the console and see if there are any errors when clicking the caret icon?

Thank you.

**Comment by RX14** [comment]
I'm using linux. There's no errors in the console, however there's a weirdness where the caret appears outside the `#settings-toggle` div: ![](https://my.mixtape.moe/mzjeac.png)

I can't fathom it myself, it appears to me *being able to click on the div at all* is the issue, not the JS. Using `$("#settings-toggle").trigger("click");` in the console works like a charm.

**Comment by bluecaret** [comment]
Thank you very much for those details! I'm still trying to figure out how to diagnose this issue, I don't have a Mac or Linux so still working at it. Getting help from a friend for it. Sorry again for the trouble.

**Comment by RX14** [comment]
@bluecaret I'd be surprised if it was different in FF57 on linux than to FF57 on windows...

**Comment by bluecaret** [comment]
@RX14 You would think so, but it works perfectly fine for me on Firefox 57 on windows...

**Comment by bluecaret** [comment]
@RX14 I believe I got this issue fixed! Update to the latest version and hopefully you should be good to go now! Thanks for the help.

**Comment by RX14** [comment]
Thanks! It works great now.
