### ISSUE TITLE
Enhancement request - 24 hour mode should always show two digit hour

### ISSUE THREAD

**Issue by kroncke-w** [bluecaret/carettab#45]
24 hr. mode does not show leading zeros for times  from 00:00 through 09:59, leading zeros option should be provided.

otherwise, working fine on firefox 57 x64.

edited: oops, title 'rewuest' should of course be 'request', i blame my fat fingers.

**Comment by bluecaret** [comment]
Thanks! I'll make sure to get that added, not sure how I missed it :)

**Comment by hiergiltdiestfu** [comment]
Bump :dancing_men:

**Comment by kroncke-w** [comment]
Re-Bump.  Been a good while since last version release.

**Comment by bluecaret** [comment]
Hi, thank you for your patience. I'm re-working CaretTab from the ground up using Angular and I'll admit, I had a bigger learning curve than I expected. I really hoped to have the next update out way before now, but I am making some good progress on it in my free time. Please be a bit more patient, it is coming and this feature request will absolutely be in it. Thank you.

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
