### ISSUE TITLE
Links are not clickable

### ISSUE THREAD

**Issue by karambaq** [bluecaret/carettab#46]
Links are not clickable in the new version. I'm using new firefox.

**Comment by bluecaret** [comment]
Thanks for the report, just got the same comment on Twitter as well. What operating system are you on? Thanks!

**Comment by karambaq** [comment]
@bluecaret I'm using Arch Linux.

**Comment by rborder** [comment]
@bluecaret Same bug here on Ubuntu 17.04

**Comment by karambaq** [comment]
Any news? Just switching from chromium to firefox

**Comment by bluecaret** [comment]
Apologies for the delay, I was hoping to get this fix in along with some other changes but those haven't been going as well. I'll split it up after all and try to get this fixed hopefully tonight.

**Comment by bluecaret** [comment]
Another day needed for this. I am combining it without another change after all. Look forward to the links working as well as the ability to add an unlimited number of links! Hoping to add it tomorrow night, end of the week at the very latest. Thank you for your patience.

**Comment by rborder** [comment]
Thanks for working on this, looking forward to the imporvements!


Richard Border
Doctoral Candidate
Institute for Behavioral Genetics
University of Colorado Boulder

**Comment by bluecaret** [comment]
This should be fixed now in the just released v2.3.1 along with the ability to add unlimited number of links.
