### ISSUE TITLE
Add system font selection

### ISSUE THREAD

**Issue by bluecaret** [bluecaret/carettab#49]
Via snusmumric on Twitter

Add option to select system fonts.

**Comment by Zangoran** [comment]
@bluecaret Any work done on this so far? I manually edited your code to allow for a font I wanted to use, but it is annoying to do this every time the extension is updated.

**Comment by bluecaret** [comment]
I have not started work on this specific feature yet. The next update will be big, and I do plan on including this feature within it, but I haven't specifically worked on this yet. If you share your code for listing the fonts, that would help me speed this up a bit :)

Thank you for your support.

**Comment by Zangoran** [comment]
@bluecaret My code was only specific to just one font, I and got it from just copying the existing code that you had already written. Sorry. But thanks for your continued development!

**Comment by Zangoran** [comment]
@bluecaret Would you mind if I gave it a go to try to add what I am looking for? I am new at development, but I think I can pull this off.

**Comment by Zangoran** [comment]
@bluecaret When I try to build using 'npm run build:chrome' I get errors, there is a problem with this command: `copy src/carettab.htm dist/ && copy -R src/assets/ dist/assets/ && copy -R src/js/vendor dist/js/vendor && copy -R src/_locales dist/_locales && copy src/js/update.js dist/js/update.js`

**Comment by bluecaret** [comment]
@Zangoran By all means give it a go! Just submit a pull request for when you have something potential working. and then I can incorporate it in the upcoming update.

As far as your build error, are you sure you have all the dependencies installed? Could you paste the full error message you are getting?

**Comment by Zangoran** [comment]
@bluecaret 
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:chrome' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prebuild:chrome', 'build:chrome', 'postbuild:chrome' ]
5 info lifecycle carettab@2.3.1~prebuild:chrome: carettab@2.3.1
6 info lifecycle carettab@2.3.1~build:chrome: carettab@2.3.1
7 verbose lifecycle carettab@2.3.1~build:chrome: unsafe-perm in lifecycle true
8 verbose lifecycle carettab@2.3.1~build:chrome: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\zach\github\carettab\node_modules\.bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Git\cmd;C:\python27;C:\Python27\Scripts;C:\Program Files\nodejs\;C:\Users\zach\AppData\Local\Microsoft\WindowsApps;C:\Users\zach\AppData\Local\atom\bin;C:\Users\zach\AppData\Local\Microsoft\WindowsApps;C:\python27;C:\Python27\Scripts;C:\Users\zach\AppData\Roaming\npm
9 verbose lifecycle carettab@2.3.1~build:chrome: CWD: C:\Users\zach\github\carettab
10 silly lifecycle carettab@2.3.1~build:chrome: Args: [ '/d /s /c',
10 silly lifecycle   'rimraf dist && npm run scss && npm run uglify && npm run copy:chrome && npm run zip:chrome' ]
11 silly lifecycle carettab@2.3.1~build:chrome: Returned: code: 1  signal: null
12 info lifecycle carettab@2.3.1~build:chrome: Failed to exec build:chrome script
13 verbose stack Error: carettab@2.3.1 build:chrome: `rimraf dist && npm run scss && npm run uglify && npm run copy:chrome && npm run zip:chrome`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid carettab@2.3.1
15 verbose cwd C:\Users\zach\github\carettab
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:chrome"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error carettab@2.3.1 build:chrome: `rimraf dist && npm run scss && npm run uglify && npm run copy:chrome && npm run zip:chrome`
22 error Exit status 1
23 error Failed at the carettab@2.3.1 build:chrome script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Zangoran** [comment]
@bluecaret Any idea on how to fix that error?

**Comment by Zangoran** [comment]
@bluecaret Fixed the errors, I downloaded and used Cygwin in order to use the cp command.

**Comment by bluecaret** [comment]
Glad you got it working! Sorry for not responding right away. This is a side hobby for me so I have limited time to work on it. I look forward to your contributions though :)

**Comment by Zangoran** [comment]
@bluecaret That is totally fine, I have the system working, but I just need to be able to remember what font was selected. How did you remember the font that was selected, so when you close the tab or open a new one, it wouldn't reset?

**Comment by bluecaret** [comment]
Use chrome.storage.sync to store the setting. You can look up the chrome extension api to learn more. Thanks!

**Comment by Zangoran** [comment]
@bluecaret Awesome, will look into it

**Comment by Zangoran** [comment]
@bluecaret I believe I have a working version available. I am just dumb, I don't know how to create a pull request. When I click on the pull request tab, no options are available. Any help would be appreciated!

**Comment by Zangoran** [comment]
@bluecaret Nevermind, figured it out, I forked and pushed my changes. Just created the pull request.

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
