### ISSUE TITLE
Extension caret tab in address bar is excessively long

### ISSUE THREAD

**Issue by kroncke-w** [bluecaret/carettab#53]
![image](https://user-images.githubusercontent.com/33828918/33524286-b4418dae-d811-11e7-8bde-d131e41851e4.png)
 extension title shows it's name in the address entry area:

 Extension (Caret T...b Clock and Date)

and takes up a lot of room. can this be shortened, possibly just to 'Caret Tab', or to dispaly the tab title string which is more useful.

**Comment by bluecaret** [comment]
Thank you for the suggestion. I'll shorten that name up. I don't think I have any other control over that for a dynamic title to match the tab title though, it is unfortunate how Firefox displays that.

Thank you.

**Comment by raksdewji** [comment]
I found a small fix for this. 

If you don't have a userChrome.css file you'll need to go and create one, I found this website which explains it nicely and easy to follow along [Creat userChrome.css](https://www.userchrome.org/how-create-userchrome-css.html)

Once you have created the userChrome.css file, edit the file and add the following: 

`/* Hide Extension Name in the identity area */
#identity-box.extensionPage #identity-icon-labels {
  display: none !important;
}`

And then just restart your browser and the name will be hidden from the address bar! Hope this helps!

**Comment by bluecaret** [comment]
Thanks for the suggestion. Looks like this is a user-specific setting and I don't think I'll be able to force this within the extension from the looks of it, but helpful nonetheless. Thanks!

**Comment by DIDIx13** [comment]
Any update or improvement ?

**Comment by bluecaret** [comment]
The name will be shortened in the next update, but I cannot get rid of it
completely.

The next update will be a large one so please be patient, I promise it will
be worth the wait!

Thanks!

**Comment by bluecaret** [comment]
I did not end up changing the name on Firefox, but it does seem like the latest version of firefox truncates that name automatically now, leaving it not taking up much space.

![Annotation 2020-08-23 221552](https://user-images.githubusercontent.com/9217636/91006453-43924e80-e58e-11ea-827b-8a081a7d0fd8.png)
