### ISSUE TITLE
Clocks in other time zones wrong

### ISSUE THREAD

**Issue by supermodularwells** [bluecaret/carettab#55]
The clocks in other time zones appear to be incorrect, at least in some cases. Currently, Sydney (Australia) is an example. It is possible this due to a lack of an adjustment for daylight savings time.

**Comment by bluecaret** [comment]
Thank you for the report, I will look into this. Daylight savings does throw a giant wrench into this stuff.

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
