### ISSUE TITLE
Feature Request: Weather

### ISSUE THREAD

**Issue by bluecaret** [bluecaret/carettab#56]
Add weather to the New Tab. As requested by several users.

**Comment by N3pp** [comment]
Any plans to add this feature in the near future?

**Comment by bluecaret** [comment]
Yes it is still "planned" though no work has been done on it. A big thing is finding an API for it that I won't have to pay for.

**Comment by bluecaret** [comment]
I'm happy to announce that this feature is now part of CaretTab as of v3.5.0 that has just been released and should become available in the next couple days in each browser!
