### ISSUE TITLE
Add more langage support ?

### ISSUE THREAD

**Issue by Halvra** [bluecaret/carettab#6]
Why not adding more langage support ? :)

**Comment by bluecaret** [comment]
Thank you for the suggestion and I will definitely put it under consideration. Unfortunately it probably wouldn't be anytime soon. I only speak English myself and am the only developer on this. But hopefully I can eventually put some time to this and get some assistance for other languages :) certainly something I would like to do at some point!

**Comment by Halvra** [comment]
I can help you for a first exemple (French langage ?) :)

**Comment by bluecaret** [comment]
Thank you Halvra, I'll take that into consideration when I get to building this :)

**Comment by mscheurer** [comment]
i guess you only need to update the date language. Can you make it variable so we can set it for us?
Like an insert field for monday - saturday...

**Comment by bluecaret** [comment]
Setting a variable for users to insert their own is a good idea!

My question is, does it just need to be the main interface itself that should be localized, or would I need to translate the settings panel as well?

**Comment by mscheurer** [comment]
No need to change the settings panel. The main interface should be enough! :+1:

**Comment by rudeigerc** [comment]
Hi,
if you want to localize settings panel, how about creating a localization file that mapping variables with words(English) as an example, and volunteers could create copies with other languages?
p.s. I can give you a hand if you need any help with Chinese😀

Best Regards

**Comment by mscheurer** [comment]
I can help you with German :)

**Comment by bluecaret** [comment]
Thanks for all the offers for help everyone! I do plan to do this, and yes I'll start by setting up a localization file for English and will let others contribute, or maybe since it isn't big sentences or anything, just use Google translate for each set of words :) I promise it is coming!

**Comment by Halvra** [comment]
I can help for french !
Localization file is a good idea. If you put it on a "localization" folder, can you make a select with all available language for easy change ?

**Comment by bluecaret** [comment]
Working on the translations now! So far I see requests for French, Chinese and Spanish. 

I may look into Russian, Portuguese and Japanese as well based on the language of reviews I have received.

To start I may just use Google Translate to get me by for now and then if anyone wants to contribute to make them better, they can :)

**Comment by bluecaret** [comment]
Okay so I tried some google translations into French line by line and it didn't seem like it was very good so... All of those who offered, the extension is ready to be translated! I already committed the code for the English translation which can be copied into a new language folder under _locales when translating.

See the English one here: https://github.com/bluecaret/carettab/blob/master/carettab/_locales/en/messages.json

Happy to accept any and all assistance with translations! Even if you can only do a little bit, that's still something in that language. Thanks everyone!

**Comment by Halvra** [comment]
Nice !
I start translation in French right now ! 👍
I will send you a pull request when all its done.

**Comment by rudeigerc** [comment]
I will start translation in Chinese (both traditional and simplified)😃

**Comment by bluecaret** [comment]
Wow that was fast guys! Thank you very very much for the help with that! I want to get some more changes into the extension this week as well but I should hopefully have a new version of the extension with these included next weekend.

And to anyone else, additional languages always welcome!

**Comment by bluecaret** [comment]
I've made a different issue for continued support of localization where I will be tracking the languages that are support and those that I'm still looking for. Since I will be tracking it there and we already have French and Chinese (THANKS!) I'm going to close this issue.

See issue #34 for continued support with this.
