### ISSUE TITLE
Custom image as a background

### ISSUE THREAD

**Issue by RX14** [bluecaret/carettab#62]
It'd be really cool to be able to set custom images as backgrounds, instead of just a solid colour. Since I see my new tab page far more than I see my desktop background (I keep firefox open on the new tab page on monitors I'm not currently using).

Been using your extension for months, and it's great. Really appreciate the work you put into it!

**Comment by bluecaret** [comment]
Thank you very much for the comments! Background images is something I am looking into. Currently working on a big update to the code itself and the interface, this might get in for that update or shortly after, but it will be a while before I can get that update out. Thanks!

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
