### ISSUE TITLE
Feature request: show day difference for extra clocks

### ISSUE THREAD

**Issue by ssorallen** [bluecaret/carettab#68]
When using multiple clocks, an indicator of +1 day or -1 day would be nice if the calendar day is different than the one of the primary clock.

**Comment by bluecaret** [comment]
Good idea, thank you! Question for you though, would you like something that says +1 or -1, or would it be better for you if each clock had it's own date as well?

**Comment by ssorallen** [comment]
I use iOS's clock app with many clocks, and I find its treatment great. It shows +/-1 day as well as the hour offset for each timezone:

![world-clock](https://user-images.githubusercontent.com/29612/36816464-cfab15c8-1d18-11e8-961b-adebf7fc0fdd.png)

**Comment by bluecaret** [comment]
Thanks for the screenshot! Great idea, I'll definitely look into this.

**Comment by ssorallen** [comment]
I implemented this feature, but it's based on branch where I worked on linting for the project. It'd be great if the linting could be merged first if you like the work, otherwise I will rebase my changes and send a different PR for them.

https://github.com/ssorallen/carettab/commit/4c5d42f9fa6c78f7126694d31257bcdb88263163

**Comment by ssorallen** [comment]
<img width="598" alt="screen shot 2018-03-01 at 10 04 44 pm" src="https://user-images.githubusercontent.com/29612/36848571-94574a4e-1d9c-11e8-9681-ddf1d5f0f1db.png">

**Comment by bluecaret** [comment]
Very much appreciate the efforts, it does look great!

Unfortunately I won't be merging this in necessarily. I am currently rewriting carettab from scratch in a separate temporary github repo so a lot of things will change, but I will definitely use your changes when I get to this part in the new version :) I apologize though, I'll admit I don't know how to use github the best, and am still learning JavaScript (if that wasn't obvious from my code lol) so the fact I am in the works to rewrite this is not obvious. Again, will definitely use this, just not via a merge.

Thanks very much!

**Comment by ssorallen** [comment]
If you'd like any help setting up the project, I am quite comfortable getting a project like this configured. You could move dependencies into the package.json's `"dependencies"`, configure linting, run a build on Travis for each pull request, and whatever else you might like.

If you want to put your code on GitHub, you can create a new branch and push it to this repo. Then we would be able to work on the same branch.

    $ git checkout -b new-branch-name # Create a new branch called "new-branch-name"
    $ git push -u origin new-branch-name # Push "new-branch-name" to this GitHub repo

**Comment by bluecaret** [comment]
Thanks @ssorallen for now I'm just trying to figure out some basic configuration, don't have a whole lot of time to commit to this now so it's slow going. Once I settle on a path, I'll put it back here as a new branch though. I'm currently using a framework that compiles the extension for different browsers automatically, so with that I got a better npm setup. Don't know about Travis, I'll look into that though.

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
