### ISSUE TITLE
Feature: Choose Search Engine to use per session

### ISSUE THREAD

**Issue by bluecaret** [bluecaret/carettab#69]
via gk liang on Chrome web store:
"Is it possible to add a search engine switch to the page because sometimes opening a new tab wants to use a different engine"

**Comment by Ruandv** [comment]
is this still something that is relevant?

**Comment by bluecaret** [comment]
No, I'm going to close this. Due to various reasons I do not plan on having this feature added, or at least for now, maybe sometime in the future.
