### ISSUE TITLE
feature request: order links by a-z

### ISSUE THREAD

**Issue by Thomas-O** [bluecaret/carettab#78]
Hi,

Would it be possible to add an option to re-order links by A-Z? Or some means by which they can be easily reordered.

Other than that everything is great. Nice to have such a simple and streamlined alternative.

Thanks for your time.

Thomas

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
