### ISSUE TITLE
Feature Request: Expose week number labels in localisation

### ISSUE THREAD

**Issue by hiergiltdiestfu** [bluecaret/carettab#80]
The options for the label for week numbers are currently fixed to "'Week', 'Wk.', '#' and ''". None of this applies to e.g. German, but these labels are not available in the localisation file. 

An appropriate selection for German would be "Woche" and "KW" (short for Kalenderwoche), while blank and the double-cross are not associated with week numbers in German.

This enhancement should expose these labels in the localisation properties files.

**Comment by bluecaret** [comment]
This will not be tied to localization instead you will be given the option of using any label you want instead. This will be in the next release.
