### ISSUE TITLE
Feature request / discussion: prefill target textbox in Links config

### ISSUE THREAD

**Issue by hiergiltdiestfu** [bluecaret/carettab#82]
This issue is related to PR #81. I would like to discuss whether it would be OK to pre-fill the link target textbox with `https://` instead of just providing the placeholder hint. 

Pros:
* Actively promotes https-Links
* Easier and quicker for users to enter new links
* Less errors in that boilerplate part of the link
* I guess almost all link targets point to http/s sites anyways

Cons:
* Might interfere with copy-past and result in unexpected `https://https://www.example.com` situations
  * Which might be countered by selecting the value of the textbox when it receives an onFocus event, so pasting is still a two-step process only.
* Communicates more strongly than a placeholder that the target box is limited to https-Links, which it is not.

**Comment by bluecaret** [comment]
First, thanks for the feedback and discussion point! :)

I'd prefer to leave it as unfilled and default to http:// for now. The extension is setup so that if there isn't an http:// added to the link, it will auto-add it for you. And defaulting to http instead of https I think should be fine as those sites that are secure will typically forward you to the secure site, the same isn't typical the opposite direction.

**Comment by hiergiltdiestfu** [comment]
Bump, since this still bothers me in the v3 beta - please reconsider :)

**Comment by bluecaret** [comment]
Hi, can you provide a counter argument to my previous reply? I still think defaulting to http is the better option as most sites will auto redirect to you https if it exists.

Granted thanks to Chrome many more sites will be https now, but a lot are not (I haven't updated my own site to https yet) and would hate to default to that possibly breaking a link especially for users who don't understand the difference.

Thanks!

**Comment by hiergiltdiestfu** [comment]
I think those users that don't understand the difference will rather use copy-paste than type in the links, so they are not hurt by a https-default/-hint.

Those users that type in the URL manually for sites that support both will benefit form being taught that it is a Good Thing to point to the encrypted endpoint.

Those users that type in the URL manually for sites that don't support https at all, will encounter a problem if they do not correct the protocol manually, either because they miss the difference, or don't understand the different. I posit that such users are not in your target audience, because installing and configuring browser extensions is not a beginners' task. In any way, almost all internet users will understand that typing in a URL relies on the URL being typed without error. Users that are actively afraid of that will usually use a search engine to switch to the target site, and will probably copy the url bar manually, or use copy-paste.

**Comment by bluecaret** [comment]
Now that I can get behind. I'm going to give it a bit more thought but I think I will probably make that switch. Thank you for your opinions!

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104

**Comment by ChristophSchmidt1203** [comment]
Looks good, thanks.
