### ISSUE TITLE
it flash when one new tab is opened.

### ISSUE THREAD

**Issue by ViGeng** [bluecaret/carettab#88]
When deep color theme is being used, it flashes when a new tab is opened. It seems like that the background color changes from white to the deep color.

**Comment by bluecaret** [comment]
Thank you. This is something I'm hoping will be smoothed out with the next update.

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
