### ISSUE TITLE
Add option to toggle "autocomplete" for search bar to hide search history.

### ISSUE THREAD

**Issue by GiantKs** [bluecaret/carettab#90]
For example, I don't want other people to see my search record, I can't do it now, I should give an option to decide whether to add autocomplete="off"，Please complete it as soon as possible。

**Comment by hiergiltdiestfu** [comment]
Do you mean the search box? I don't get autocompletion in that box. Are you sure this isn't your browser's behaviour? 

Btw, missing features are not usually called bugs, but developers usually are happy to accept feature requests.

**Comment by GiantKs** [comment]
Yeah, it should be a problem with the product, I'm sorry;This is the default behavior for input, but I recommend that you add a feature in the Settings panel that allows you to choose whether or not to auto-complete the input, which you can add on the input TAB autocomplete =“off”，This problem caused me trouble using it.

**Comment by bluecaret** [comment]
Hi, thanks for the suggestion, I'll be sure to add it in the future.

**Comment by GiantKs** [comment]
good

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
