### ISSUE TITLE
Settings doesn't sync between tabs & makes the history instances blink

### ISSUE THREAD

**Issue by Regnander** [bluecaret/carettab#92]
The settings doesn't synchronize between tabs, which is making the log instance in the history blink irregularly.

![ct-1](https://user-images.githubusercontent.com/17113053/45209800-27f0e900-b28e-11e8-8f8c-c82d99781af8.gif)

How to reproduce:
1. Open two new tabs.
2. Go to the Extras tab in the settings
3. Change the Tab Title so the two tabs have different titles.

Alternatively, and if this is possible, disabling the history logging of the new tabs would be nice, since I don't find it interesting to see when I opened a new tab in my history.

**Comment by bluecaret** [comment]
This appears to be resolved after the latest update.
