### ISSUE TITLE
The default input box caused by Chrome is ugly

### ISSUE THREAD

**Issue by loveniconico** [bluecaret/carettab#93]
![image](https://user-images.githubusercontent.com/37494315/45254100-a8a20900-b3a4-11e8-8e18-531fe335e1bc.png)
不知道您懂不懂中文，但是我肯定不懂英文，所以先说声对不起。下面是问题的描述：
标题的中文：Chrome默认样式导致的输入框丑陋
正如图所示，界面有点丑，当然不是您的而是Chrome默认的快速填充的样式真的很丑，这个能解决吗？

Google Translate：`As shown in the figure, the interface is a bit ugly, of course not yours, but Chrome's default fast-filling style is really ugly, can this be solved?`

**Comment by bluecaret** [comment]
I'll leave this here as a feature request but it will be low priority as it isn't simple to change. Thank you.

**Comment by bluecaret** [comment]
I believe this has been fixed now.
