### ISSUE TITLE
Update??

### ISSUE THREAD

**Issue by da411d** [bluecaret/carettab#94]
When new update will be published on Chrome Web Store?)

**Comment by bluecaret** [comment]
Hello, the next update is still in the works. I made some big progress with it this last week but it still has more to get done. 

I apologise for the delay. Ive been wanting to rewrite it from scratch using a framework and had some learning curves to figure out and some failed attempts here and there, but I have settled on one and have figured out how to work with it for the extensions needs so work should hopefully start going faster now. I'm starting to see some light at the end of the tunnel! 

Once this gets out I expect updates to happen more frequently again. Thank you for your patience.

**Comment by da411d** [comment]
Are you still alive?🙂🙃

**Comment by bluecaret** [comment]
Still alive :) I'm trying to fit in coding this update (complete rework) in my free time while trying not to hate the project. Hope you understand. Please be assured that work IS being done on this though.

**Comment by bluecaret** [comment]
Hi, if you are interested, there is now a beta of the new update available. Check out #104 for details.
