### ISSUE TITLE
GMT time is wrong

### ISSUE THREAD

**Issue by CYUlysses** [bluecaret/carettab#95]
GMT time should be the same as UTC, but currently when I choose GMT it is one hour ahead of UTC.
(While most other GMT+n zones are okay)

Possible cause: the "GMT" time is synchronized with certain country's time, but that country actually switches off to a different time zone (e.g. British Summer Time BST) during summer.

Big issue. Please fix.

**Comment by bluecaret** [comment]
There have been a few issues with timezone selection being correct. I tried to condense the timezones into a small list that is easier to search through but have been learning that it just isn't a good idea to generalize timezones like that :) the next update will consist of much more timezone options that should hopefully correct this issue. I'll look into it to double check though. 

For now as a workaround you can try selecting the timezone next to it to compensate for the difference. Thank you for the bug report.

**Comment by windghoul** [comment]
I found that the time in the +1 time zone and the +2 time zone are the same, and the time in the -11 time zone and the +12 time zone is also the same. Is the problem here? The time here is wrong, causing the time of the entire list to be garbled, so the GMT time is incorrect.
thanks

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
