### ISSUE TITLE
Enhancement: rearranging links

### ISSUE THREAD

**Issue by bertold** [bluecaret/carettab#96]
It would be really nice if the links displayed could be sorted or rearranged.

**Comment by bluecaret** [comment]
Thanks for the suggestion, this will be in the next update :)

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
